#!/usr/bin/env bash
# Rebuild only the SDK/CRT-free fiber/FLS fixture group.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-fibers.XXXXXX")"
cleanup() {
    for name in core migrate state stack thread-exit thread-forced process-exit process-forced state-asm grow-asm; do
        rm -f "$task_dir/$name.obj"
    done
    rm -f "$task_dir/kernel32.lib" "$task_dir/discard.lib" "$task_dir/discard.exp"
    rmdir "$task_dir"
}
trap cleanup EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=.)
cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; suffix=-x86; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; suffix=; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; suffix=; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    mkdir -p "bin/$arch"
    "$dlltool_bin" -m "$dllmachine" -k -d "src/kernel32$suffix.def" -l "$task_dir/kernel32.lib"
    "$clang_bin" --target="$target" -c src/state.S -o "$task_dir/state-asm.obj"
    "$clang_bin" --target="$target" -c src/grow.S -o "$task_dir/grow-asm.obj"
    for program in core migrate state stack thread-exit thread-forced process-exit process-forced; do
        define=(); assembly=(); source="$program"
        case "$program" in
            state) assembly=("$task_dir/state-asm.obj");;
            stack) assembly=("$task_dir/grow-asm.obj");;
            thread-exit) source=exits;;
            thread-forced) source=exits; define=(-DFORCED_THREAD);;
            process-exit) source=exits; define=(-DPROCESS_NORMAL);;
            process-forced) source=exits; define=(-DPROCESS_FORCED);;
        esac
        "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" "${define[@]}" \
            -c "src/$source.c" -o "$task_dir/$program.obj"
        "$link_bin" /machine:"$machine" /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
            /entry:entry /subsystem:console /stack:1048576,4096 /heap:1048576,4096 \
            /implib:"$task_dir/discard.lib" /out:"bin/$arch/$program.exe" \
            "$task_dir/$program.obj" "${assembly[@]}" "$task_dir/kernel32.lib"
    done
done
{
    printf '# Generated by fibers/build.sh; native Windows execution unknown.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    for tool in clang linker dlltool; do
        case "$tool" in clang) executable="$clang_bin";; linker) executable="$link_bin";; dlltool) executable="$dlltool_bin";; esac
        printf '%s_sha256 = "%s"\n' "$tool" "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    printf 'dlltool_identity = "llvm-dlltool has no version flag; executable SHA-256 identifies the installed tool"\n'
    printf 'oracle = "Microsoft public fiber/FLS/ABI contracts; labeled conversion/forced-cleanup personality policy; no native Windows differential run"\n'
    printf 'expected_exit = 0\n'
    for source in build.sh src/*.c src/*.h src/*.S src/*.def; do
        printf '\n[[source]]\npath = "%s"\n' "$source"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    for arch in x86 x64 arm64; do
        for name in core migrate state stack thread-exit thread-forced process-exit process-forced; do
            printf '\n[[fixture]]\narch = "%s"\npath = "bin/%s/%s.exe"\n' "$arch" "$arch" "$name"
            printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/$name.exe" | cut -d' ' -f1)"
            printf 'bytes = %s\n' "$(wc -c < "bin/$arch/$name.exe" | tr -d ' ')"
        done
    done
} > manifest.toml
