//! Replays the Cortex-M4 differential corpus: each case's post-state as QEMU
//! `mps2-an386` computed it (`tests/generated/cortex_m/thumb_oracle.json`,
//! generated by `tools/cortex-m-diff/qemu_oracle.py`).
//!
//! Policy differences from the oracle, which runs the whole firmware:
//! - An UNDEFINED encoding is returned to the embedder here, where the
//!   processor takes a UsageFault (escalated to HardFault).
//! - A BKPT escalated to HardFault sets HFSR.DEBUGEVT (Armv7-M ARM C1.5,
//!   "HardFault on breakpoint (BKPT) escalation"); QEMU sets HFSR.FORCED.

use std::sync::Arc;

use serde_json::Value;
use vm_memory::{Bytes, GuestAddress, GuestMemoryMmap};

use super::*;
use crate::isa::arm::cortex_m::scb::{cfsr, hfsr};
use crate::vm::vcpu::CortexMRegisters;

const ORACLE: &str = include_str!("../../../tests/generated/cortex_m/thumb_oracle.json");

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn u32_of(v: &Value) -> u32 {
    v.as_u64().unwrap() as u32
}

fn words(v: &Value) -> Vec<u32> {
    v.as_array().unwrap().iter().map(u32_of).collect()
}

/// `pattern` with the oracle's `[offset, byte]` changes applied.
fn patched(pattern: &[u8], changes: &Value) -> Vec<u8> {
    let mut bytes = pattern.to_vec();
    for change in changes.as_array().unwrap() {
        bytes[change[0].as_u64().unwrap() as usize] = change[1].as_u64().unwrap() as u8;
    }
    bytes
}

fn read(mem: &GuestMemoryMmap, addr: u64, len: usize) -> Vec<u8> {
    let mut bytes = vec![0u8; len];
    mem.read_slice(&mut bytes, GuestAddress(addr)).unwrap();
    bytes
}

/// Runs one case and describes every difference from the oracle.
fn replay(doc: &Value, case: &Value) -> Vec<String> {
    let data_base = doc["data_base"].as_u64().unwrap();
    let stack_base = doc["stack_base"].as_u64().unwrap();
    let data_pattern = hex(doc["data_pattern"].as_str().unwrap());
    let stack_pattern = hex(doc["stack_pattern"].as_str().unwrap());
    let fault_handler = u32_of(&doc["fault_handler"]);

    let mem = Arc::new(
        GuestMemoryMmap::<()>::from_ranges(&[
            (GuestAddress(0), 0x4_0000),
            (GuestAddress(0x2000_0000), 0x1_0000),
        ])
        .unwrap(),
    );
    let handler = &doc["svc_handler"];
    for (base, code) in [
        (0, &doc["vector_table"]),
        (handler["base"].as_u64().unwrap(), &handler["code"]),
        (case["code_base"].as_u64().unwrap(), &case["code"]),
    ] {
        mem.write_slice(&hex(code.as_str().unwrap()), GuestAddress(base))
            .unwrap();
    }
    mem.write_slice(&data_pattern, GuestAddress(data_base))
        .unwrap();
    mem.write_slice(&stack_pattern, GuestAddress(stack_base))
        .unwrap();

    let initial = words(&doc["vectors"][case["vector"].as_u64().unwrap() as usize]);
    let end = u32_of(&case["end"]);
    let mut vcpu = CortexMVcpu::new(0, mem.clone());
    let mut regs = CortexMRegisters::default();
    regs.r.copy_from_slice(&initial[..13]);
    regs.lr = initial[13];
    regs.msp = u32_of(&doc["stack_top"]);
    regs.pc = u32_of(&case["start"]);
    regs.xpsr = u32_of(&case["apsr"]) | (1 << 24);
    vcpu.set_state(&CpuState::cortex_m(regs, Default::default()))
        .unwrap();

    let mut error = None;
    for _ in 0..64 {
        let pc = vcpu.current_pc() as u32;
        if pc == end || pc == fault_handler {
            break;
        }
        if let Err(e) = vcpu.step_insn() {
            error = Some(e);
            break;
        }
    }
    let CpuState::CortexM(state) = vcpu.get_state().unwrap() else {
        unreachable!()
    };
    let (regs, sregs) = (state.regs, state.sregs);
    let pc = regs.pc;
    let mut diffs = Vec::new();
    let mut check = |what: &str, got: u32, want: u32| {
        if got != want {
            diffs.push(format!("{what}={got:#x} want {want:#x}"));
        }
    };
    let expect = &case["expect"];
    if let Some(fault) = expect.get("fault") {
        let status = u32_of(&fault["cfsr"]);
        if status & (cfsr::UNDEFINSTR | cfsr::NOCP) != 0 {
            if !matches!(error, Some(Error::InvalidInstruction { .. })) {
                diffs.push(format!(
                    "expected an invalid-instruction error, got {error:?}"
                ));
            }
            return diffs;
        }
        if let Some(e) = error {
            return vec![format!("error {e}")];
        }
        check("pc", pc, fault_handler);
        check("ipsr", regs.xpsr & 0x1FF, u32_of(&fault["ipsr"]));
        check("cfsr", sregs.cfsr, status);
        let mut want_hfsr = u32_of(&fault["hfsr"]);
        if case["text"].as_str().unwrap().starts_with("bkpt") {
            want_hfsr = hfsr::DEBUGEVT;
        }
        check("hfsr", sregs.hfsr, want_hfsr);
        check("msp", regs.msp, u32_of(&fault["msp"]));
        check("exc_return", regs.lr, u32_of(&fault["exc_return"]));
        let frame = read(&mem, u64::from(regs.msp), 32);
        for (i, want) in words(&fault["frame"]).iter().enumerate() {
            let got = u32::from_le_bytes(frame[4 * i..4 * i + 4].try_into().unwrap());
            check(&format!("frame[{i}]"), got, *want);
        }
        return diffs;
    }
    if let Some(e) = error {
        return vec![format!("error {e}")];
    }
    if pc != end {
        return vec![format!("stopped at {pc:#x}, not {end:#x}")];
    }
    for (i, want) in words(&expect["r"]).iter().enumerate() {
        check(&format!("r{i}"), regs.r[i], *want);
    }
    check("lr", regs.lr, u32_of(&expect["lr"]));
    let sp = u32_of(&expect["sp"]);
    check("sp", regs.msp, sp);
    check("apsr", regs.xpsr & 0xF80F_0000, u32_of(&expect["apsr"]));
    check("ipsr", regs.xpsr & 0x1FF, 0);
    if read(&mem, data_base, 256) != patched(&data_pattern, &expect["data"]) {
        diffs.push("data memory".into());
    }
    let live = (u64::from(sp).saturating_sub(stack_base)).min(256) as usize;
    let stack = read(&mem, stack_base, 256);
    if stack[live..] != patched(&stack_pattern, &expect["stack"])[live..] {
        diffs.push("stack memory".into());
    }
    diffs
}

#[test]
fn cortex_m4_matches_the_qemu_oracle() {
    let doc: Value = serde_json::from_str(ORACLE).unwrap();
    let cases = doc["cases"].as_array().unwrap();
    // The corpus is not vacuous: every instruction class, both results.
    assert!(cases.len() >= 1_300, "{} cases", cases.len());
    let faults = cases
        .iter()
        .filter(|c| c["expect"].get("fault").is_some())
        .count();
    assert!(faults >= 20, "{faults} fault cases");
    let mut failures = Vec::new();
    for case in cases {
        let diffs = replay(&doc, case);
        if !diffs.is_empty() {
            failures.push(format!(
                "{:?} (state {}): {}",
                case["text"].as_str().unwrap(),
                case["vector"],
                diffs.join(", ")
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from {}:\n{}",
        failures.len(),
        cases.len(),
        doc["oracle"],
        failures[..failures.len().min(40)].join("\n")
    );
}
