#!/usr/bin/env bash
# Rebuilds the morok program corpus from src/ and rewrites manifest.toml.
#
# Requirements: Zig 0.16.0 (its bundled clang, musl, and libc++ provide the
# Linux cross toolchains). Run from anywhere:
#
#     tests/fixtures/user/linux/programs/build.sh
#
# The flags are morok's (`-O2`, `-std=c11` or `-std=c++23`, `-D_GNU_SOURCE`,
# `-lm`), plus a static, stripped, sanitizer-free link so that no guest
# sysroot is needed. The manifest records the toolchain, flags, and SHA-256
# of every output; the user_linux test verifies the hashes before running
# anything.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

zig_version="$(zig version)"
if [[ "$zig_version" != "0.16.0" ]]; then
    echo "error: Zig 0.16.0 is required (found $zig_version)" >&2
    exit 1
fi

targets=(x86_64-linux-musl aarch64-linux-musl riscv64-linux-musl)
flags=(-static -O2 -s -fno-sanitize=all -D_GNU_SOURCE -ffile-prefix-map="$here"=.)
# Every program named in cases.txt, in its order.
programs=()
while read -r name _; do
    [[ -z "$name" || "$name" == \#* ]] && continue
    programs+=("$name")
done < cases.txt

manifest="manifest.toml"
{
    echo "# Generated by build.sh; do not edit."
    echo "toolchain = \"zig $zig_version\""
    recorded="${flags[*]}"
    printf 'flags = "%s"\n' "${recorded//$here/<corpus-dir>}"
    echo "c = \"zig cc -std=c11 <flags> -lm\""
    echo "cxx = \"zig c++ -std=c++23 <flags> -lm\""
    echo
} > "$manifest"

for target in "${targets[@]}"; do
    arch="${target%%-*}"
    mkdir -p "bin/$arch"
    for prog in "${programs[@]}"; do
        if [[ -f "src/$prog.c" ]]; then
            src="src/$prog.c"
            cc=(zig cc -std=c11)
        else
            src="src/$prog.cpp"
            cc=(zig c++ -std=c++23)
        fi
        out="bin/$arch/$prog"
        "${cc[@]}" -target "$target" "${flags[@]}" -o "$out" "$src" -lm
        sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
        {
            echo "[[fixture]]"
            echo "path = \"$out\""
            echo "source = \"$src\""
            echo "target = \"$target\""
            echo "sha256 = \"$sum\""
            echo
        } >> "$manifest"
    done
done
echo "built ${#targets[@]} targets x ${#programs[@]} programs"
