#!/usr/bin/env bash
# Build only custom-entry CRT fixtures, using generated import stubs, no CRT/SDK blobs.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-crt.XXXXXX")"
programs=(foundation errno module invalid fatal)
cleanup() {
    for program in "${programs[@]}"; do rm -f "$task_dir/$program.obj"; done
    for group in kernel32 heap string runtime extra abi discard; do
        rm -f "$task_dir/$group.lib" "$task_dir/$group.obj" "$task_dir/$group.exp"
    done
    rmdir "$task_dir"
}
trap cleanup EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=.)
cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; suffix=-x86; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; suffix=; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; suffix=; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    "$dlltool_bin" -m "$dllmachine" -k -d "src/kernel32$suffix.def" -l "$task_dir/kernel32.lib"
    "$clang_bin" --target="$target" -c src/abi.S -o "$task_dir/abi.obj"
    for binding in msvcrt ucrtbase apiset; do
        mkdir -p "bin/$arch/$binding"
        case "$binding" in
            msvcrt) define=(-DLEGACY_CRT);;
            ucrtbase) define=();;
            apiset) define=(-DAPISET_CRT);;
        esac
        for group in heap string runtime; do
            if [[ "$binding" == apiset ]]; then dll="api-ms-win-crt-$group-l1-1-0.dll"; else dll="$binding.dll"; fi
            "$dlltool_bin" -m "$dllmachine" -D "$dll" -d "src/$group.def" -l "$task_dir/$group.lib"
        done
        if [[ "$binding" == apiset ]]; then extra_dll=vcruntime140.dll; else extra_dll="$binding.dll"; fi
        "$dlltool_bin" -m "$dllmachine" -D "$extra_dll" -d src/extra.def -l "$task_dir/extra.lib"
        for program in "${programs[@]}"; do
            if [[ "$binding" == msvcrt && ( "$program" == invalid || "$program" == fatal ) ]]; then continue; fi
            assembly=()
            if [[ "$program" == module ]]; then assembly=("$task_dir/abi.obj"); fi
            "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" "${define[@]}" \
                -c "src/$program.c" -o "$task_dir/$program.obj"
            "$link_bin" /machine:"$machine" /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
                /entry:entry /subsystem:console /stack:1048576,4096 /heap:1048576,4096 \
                /implib:"$task_dir/discard.lib" /out:"bin/$arch/$binding/$program.exe" \
                "$task_dir/$program.obj" "${assembly[@]}" "$task_dir/kernel32.lib" \
                "$task_dir/heap.lib" "$task_dir/string.lib" "$task_dir/runtime.lib" "$task_dir/extra.lib"
        done
    done
done
{
    printf '# Generated by crt/build.sh; no native Windows execution oracle.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    for tool in clang linker dlltool; do
        case "$tool" in clang) executable="$clang_bin";; linker) executable="$link_bin";; dlltool) executable="$dlltool_bin";; esac
        printf '%s_sha256 = "%s"\n' "$tool" "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    printf 'dlltool_identity = "llvm-dlltool has no version flag; installed executable pinned by SHA-256"\n'
    printf 'oracle = "Retained Microsoft CRT/ABI contracts plus explicitly labeled personality policies, not normal CRT startup or native differential results"\n'
    for source in build.sh src/*.c src/*.h src/*.def src/*.S; do
        printf '\n[[source]]\npath = "%s"\n' "$source"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    for arch in x86 x64 arm64; do
        for binding in msvcrt ucrtbase apiset; do
            for program in "${programs[@]}"; do
                if [[ "$binding" == msvcrt && ( "$program" == invalid || "$program" == fatal ) ]]; then continue; fi
                printf '\n[[fixture]]\narch = "%s"\nbinding = "%s"\npath = "bin/%s/%s/%s.exe"\n' "$arch" "$binding" "$arch" "$binding" "$program"
                printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/$binding/$program.exe" | cut -d' ' -f1)"
                printf 'bytes = %s\n' "$(wc -c < "bin/$arch/$binding/$program.exe" | tr -d ' ')"
                if [[ "$program" == fatal ]]; then printf 'expected_exit = 3221226505\n'; else printf 'expected_exit = 0\n'; fi
            done
        done
    done
} > manifest.toml
