#!/usr/bin/env ruby
# Mechanical conversion of Microsoft's retained Windows BestFit CP1252 table.
# Unicode data license: docs/specifications/windows/crt-startup/unicode/LICENSE.
require 'digest'

ROOT = File.expand_path('../..', __dir__)
INPUT = File.join(ROOT, 'docs/specifications/windows/crt-startup/unicode/bestfit1252.txt')
OUTPUT = File.join(ROOT, 'src/user/windows/dll/crt/startup/codepage_data.rs')
SHA = '72ea23c939c5b26fae7aded0207b327e2f3902d7d3c168d7087f5cfc38ee76a9'
raw = File.binread(INPUT)
abort 'retained input SHA mismatch' unless Digest::SHA256.hexdigest(raw) == SHA
records = raw.each_line.map { |line| line.split(';', 2).first.to_s.split }.reject(&:empty?)
abort 'not Windows CP1252' unless records.shift == %w[CODEPAGE 1252]
abort 'unexpected CPINFO' unless records.shift.map(&:downcase) == %w[cpinfo 1 0x3f 0x003f]
tables = {}
%w[MBTABLE WCTABLE].each do |tag|
  header = records.shift
  abort "missing #{tag}" unless header && header[0] == tag
  count = Integer(header[1], 10)
  tables[tag] = records.shift(count).map do |row|
    abort "invalid #{tag} row" unless row.length == 2
    row.map { |value| Integer(value, 16) }
  end
  abort "duplicate #{tag} keys" unless tables[tag].map(&:first).uniq.length == count
end
abort 'trailing data' unless records == [%w[ENDCODEPAGE], ["\x1A"]]
mb = tables.fetch('MBTABLE').sort
wc = tables.fetch('WCTABLE').sort
abort 'unexpected table widths/counts' unless mb.length == 256 && wc.length == 698 &&
  mb.map(&:first) == (0..255).to_a && mb.all? { |_, unit| (0..0xffff).cover?(unit) } &&
  wc.all? { |unit, byte| (0..0xffff).cover?(unit) && (0..255).cover?(byte) }
out = "// @generated by tools/windows/generate_cp1252.rb; do not hand-edit.\n" \
      "// Input SHA-256: #{SHA}\n" \
      "// Windows BestFit CP1252, MBTABLE=256 / WCTABLE=698.\n" \
      "// Associated Unicode copyright/permission notice:\n" \
      "// docs/specifications/windows/crt-startup/unicode/LICENSE.\n\n" \
      "pub(super) const DECODE: [u16; 256] = [\n"
mb.each_slice(12) { |rows| out << '    ' + rows.map { |_, unit| format('0x%04X', unit) }.join(', ') + ",\n" }
out << "];\n\npub(super) const ENCODE: [(u16, u8); 698] = [\n"
wc.each { |unit, byte| out << format("    (0x%04X, 0x%02X),\n", unit, byte) }
out << "];\n"
if ARGV == ['--check']
  abort 'generated output differs' unless File.binread(OUTPUT) == out
elsif ARGV.empty?
  File.binwrite(OUTPUT, out)
else
  abort 'usage: generate_cp1252.rb [--check]'
end
puts "CP1252: 256 decode + 698 encode mappings; #{Digest::SHA256.hexdigest(out)}"
