#!/usr/bin/env bash
set -euo pipefail

fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-seh-x86.XXXXXX")"
trap 'rm -f "$task_dir/unwind.obj" "$task_dir/kernel32.lib"; rmdir "$task_dir"' EXIT

clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"

cd "$fixture_dir"
mkdir -p bin
"$dlltool_bin" -m i386 -k -d src/kernel32.def -l "$task_dir/kernel32.lib"
"$clang_bin" --target=i686-pc-windows-msvc -c src/unwind.S -o "$task_dir/unwind.obj"
"$link_bin" /machine:x86 /entry:entry /subsystem:console /nodefaultlib \
    /timestamp:0 /dynamicbase /nxcompat /safeseh:no /stack:1048576,4096 \
    /out:bin/unwind.exe "$task_dir/unwind.obj" "$task_dir/kernel32.lib"

{
    printf '# Generated by build.sh; expected status follows the documented RtlUnwind contract.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'source_sha256 = "%s"\n' "$(shasum -a 256 src/unwind.S | cut -d' ' -f1)"
    printf 'def_sha256 = "%s"\n' "$(shasum -a 256 src/kernel32.def | cut -d' ' -f1)"
    printf 'image_sha256 = "%s"\n' "$(shasum -a 256 bin/unwind.exe | cut -d' ' -f1)"
    printf 'image_bytes = %s\n' "$(wc -c < bin/unwind.exe | tr -d ' ')"
    printf 'expected_status = 0\n'
} > manifest.toml
