#!/usr/bin/env bash
# Rebuild one freestanding ARM64 PE using only Clang, llvm-dlltool, and LLD.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
work_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-arm64-pac-unwind.XXXXXX")"
cleanup() {
    rm -f "$work_dir/pac.obj" "$work_dir/kernel32.lib" "$work_dir/discard.lib"
    rmdir "$work_dir"
}
trap cleanup EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
cd "$fixture_dir"
"$dlltool_bin" -m arm64 -D KERNEL32.dll -d src/kernel32.def -l "$work_dir/kernel32.lib"
"$clang_bin" --target=aarch64-pc-windows-msvc -c -ffile-prefix-map="$fixture_dir"=. \
    src/pac.S -o "$work_dir/pac.obj"
"$link_bin" /machine:arm64 /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
    /entry:entry /subsystem:console /stack:1048576,4096 /heap:1048576,4096 \
    /implib:"$work_dir/discard.lib" /out:bin/arm64/pac.exe \
    "$work_dir/pac.obj" "$work_dir/kernel32.lib"
{
    printf '# Generated by arm64_pac_unwind/build.sh; no native Windows oracle.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    for tool in clang linker dlltool; do
        case "$tool" in
            clang) executable="$clang_bin";;
            linker) executable="$link_bin";;
            dlltool) executable="$dlltool_bin";;
        esac
        printf '%s_sha256 = "%s"\n' "$tool" "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    for source in build.sh src/kernel32.def src/pac.S; do
        printf '\n[[source]]\npath = "%s"\nsha256 = "%s"\n' \
            "$source" "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    printf '\n[[fixture]]\npath = "bin/arm64/pac.exe"\n'
    printf 'sha256 = "%s"\n' "$(shasum -a 256 bin/arm64/pac.exe | cut -d' ' -f1)"
    printf 'bytes = %s\n' "$(wc -c < bin/arm64/pac.exe | tr -d ' ')"
    printf 'expected_exit = 0\n'
} > manifest.toml
