#!/usr/bin/env bash
# Only owned generated artifacts; custom entry is distinct from ordinary CRT startup.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository="$(cd "$fixture_dir/../../../../.." && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-crt-stdio.XXXXXX")"
programs=(streams bytes descriptors translation repair buffering errors)
cleanup() {
    for program in "${programs[@]}" ordinary; do rm -f "$task_dir/$program.obj"; done
    for group in kernel32 stdio access narrow runtime; do rm -f "$task_dir/$group.lib" "$task_dir/$group.exp"; done
    rmdir "$task_dir"
}
trap cleanup EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
readobj_bin="${LLVM_READOBJ_BIN:-llvm-readobj}"
zig_bin="${ZIG_BIN:-zig}"
gcc_x86="${GCC_X86_BIN:-/opt/homebrew/Cellar/mingw-w64/14.0.0_3/toolchain-i686/bin/i686-w64-mingw32-gcc}"
gcc_x64="${GCC_X64_BIN:-/opt/homebrew/Cellar/mingw-w64/14.0.0_3/toolchain-x86_64/bin/x86_64-w64-mingw32-gcc}"
[[ "$("$zig_bin" version)" == 0.16.0 ]] || { echo 'Expected Zig 0.16.0 provenance' >&2; exit 1; }
for compiler in "$gcc_x86" "$gcc_x64"; do
    [[ "$("$compiler" -dumpfullversion)" == 16.2.0 ]] || { echo 'Expected MinGW GCC 16.2.0' >&2; exit 1; }
done
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=. -ffile-prefix-map="$repository"=repository)
cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; suffix=-x86; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; suffix=; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; suffix=; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    "$dlltool_bin" -m "$dllmachine" -k -d "src/kernel32$suffix.def" -l "$task_dir/kernel32.lib"
    for binding in msvcrt ucrtbase apiset; do
        case "$binding" in
            msvcrt) dll=msvcrt.dll; define=(-DLEGACY); access="legacy$suffix";;
            ucrtbase) dll=ucrtbase.dll; define=(); access=ucrt;;
            apiset) dll=api-ms-win-crt-stdio-l1-1-0.dll; define=(-DAPISET); access=ucrt;;
        esac
        "$dlltool_bin" -m "$dllmachine" -D "$dll" -d src/stdio.def -l "$task_dir/stdio.lib"
        "$dlltool_bin" -m "$dllmachine" -D "$dll" -d "src/$access.def" -l "$task_dir/access.lib"
        libraries=("$task_dir/kernel32.lib" "$task_dir/stdio.lib" "$task_dir/access.lib")
        if [[ "$binding" != apiset ]]; then
            "$dlltool_bin" -m "$dllmachine" -D "$dll" -d src/narrow.def -l "$task_dir/narrow.lib"
            libraries+=("$task_dir/narrow.lib")
        fi
        if [[ "$binding" != msvcrt ]]; then
            runtime_dll=ucrtbase.dll
            [[ "$binding" != apiset ]] || runtime_dll=api-ms-win-crt-runtime-l1-1-0.dll
            "$dlltool_bin" -m "$dllmachine" -D "$runtime_dll" -d src/runtime.def -l "$task_dir/runtime.lib"
            libraries+=("$task_dir/runtime.lib")
        fi
        mkdir -p "bin/$arch/$binding"
        for program in "${programs[@]}"; do
            [[ "$binding" != msvcrt || "$program" != errors ]] || continue
            "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" "${define[@]}" \
                -c "src/$program.c" -o "$task_dir/$program.obj"
            "$link_bin" /machine:"$machine" /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
                /entry:entry /subsystem:console /stack:1048576,4096 /heap:1048576,4096 \
                /out:"bin/$arch/$binding/$program.exe" "$task_dir/$program.obj" "${libraries[@]}"
        done
    done
    mkdir -p "bin/$arch/ordinary" observations
    for kind in main wmain; do
        wide=(); [[ "$kind" != wmain ]] || wide=(-DWIDE -municode)
        output="bin/$arch/ordinary/$kind.exe"
        if [[ "$arch" == arm64 ]]; then
            "$zig_bin" cc -target aarch64-windows-gnu -Os -fno-ident \
                -ffile-prefix-map="$fixture_dir"=. -ffile-prefix-map="$repository"=repository \
                -s "${wide[@]}" src/ordinary.c -o "$output"
        else
            if [[ "$arch" == x86 ]]; then compiler="$gcc_x86"; else compiler="$gcc_x64"; fi
            "$compiler" -Os -fno-ident -ffile-prefix-map="$fixture_dir"=. \
                -ffile-prefix-map="$repository"=repository -Wl,--no-insert-timestamp \
                -Wl,--strip-all "${wide[@]}" src/ordinary.c -o "$output"
        fi
        "$readobj_bin" --file-headers --coff-imports "$output" > "observations/$arch-$kind.txt"
    done
done
{
    printf '# Generated by crt_stdio/build.sh; native Windows execution unknown.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'zig = "%s"\n' "$("$zig_bin" version)"
    printf 'custom_entry = "entry; no CRT startup object"\n'
    printf 'ordinary_gcc_recipe = "GCC -Os -fno-ident -ffile-prefix-map={fixture}=. -ffile-prefix-map={repository}=repository -Wl,--no-insert-timestamp -Wl,--strip-all [-DWIDE -municode] src/ordinary.c -o {output}"\n'
    printf 'ordinary_zig_recipe = "zig cc -target aarch64-windows-gnu -Os -fno-ident -ffile-prefix-map={fixture}=. -ffile-prefix-map={repository}=repository -s [-DWIDE -municode] src/ordinary.c -o {output}"\n'
    for tool in clang linker dlltool readobj zig gcc_x86 gcc_x64; do
        case "$tool" in clang) executable="$clang_bin";; linker) executable="$link_bin";; dlltool) executable="$dlltool_bin";; readobj) executable="$readobj_bin";; zig) executable="$zig_bin";; gcc_x86) executable="$gcc_x86";; gcc_x64) executable="$gcc_x64";; esac
        printf '%s_sha256 = "%s"\n' "$tool" "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    printf 'oracle = "Independent literal bytes and Microsoft public contracts plus named producer inventories; native oracle unknown"\n'
    for source in build.sh baseline.sh README.md src/*.c src/*.h src/*.def ../layout/public.c \
        ../../../../../docs/specifications/windows/crt-startup/mingw14/winnt-exception-context-excerpt.h \
        ../../../../../docs/specifications/windows/crt-startup/zig/winnt-exception-context-excerpt.h; do
        printf '\n[[source]]\npath = "%s"\n' "$source"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    for arch in x86 x64 arm64; do
        for binding in msvcrt ucrtbase apiset; do
            for program in "${programs[@]}"; do
                [[ "$binding" != msvcrt || "$program" != errors ]] || continue
                path="bin/$arch/$binding/$program.exe"
                printf '\n[[fixture]]\narch = "%s"\nbinding = "%s"\nprogram = "%s"\npath = "%s"\n' "$arch" "$binding" "$program" "$path"
                printf 'sha256 = "%s"\nbytes = %s\nexpected_exit = 0\nrole = "custom-entry"\n' \
                    "$(shasum -a 256 "$path" | cut -d' ' -f1)" "$(wc -c < "$path" | tr -d ' ')"
            done
        done
        for kind in main wmain; do
            path="bin/$arch/ordinary/$kind.exe"
            printf '\n[[fixture]]\narch = "%s"\nbinding = "compiler-selected"\nprogram = "%s"\npath = "%s"\n' "$arch" "$kind" "$path"
            printf 'sha256 = "%s"\nbytes = %s\nrole = "ordinary-startup-observation"\n' \
                "$(shasum -a 256 "$path" | cut -d' ' -f1)" "$(wc -c < "$path" | tr -d ' ')"
            printf 'producer = "%s"\n' "$([[ "$arch" == arm64 ]] && echo 'Zig 0.16.0 bundled MinGW' || echo 'MinGW-w64 14.0.0 GCC 16.2.0')"
            printf 'iat_path = "observations/%s-%s.txt"\niat_sha256 = "%s"\n' "$arch" "$kind" \
                "$(shasum -a 256 "observations/$arch-$kind.txt" | cut -d' ' -f1)"
        done
    done
} > manifest.toml
