#!/usr/bin/env bash
# Rebuilds the rax-user Linux fixtures from src/ and rewrites manifest.toml.
#
# Requirements: Zig 0.16.0 (its bundled musl and clang provide the Linux
# cross toolchains). Run from anywhere:
#
#     tests/fixtures/user/linux/build.sh
#
# Binaries are static, stripped, position-dependent executables (i386 for
# a subset, listed below). The
# manifest records the toolchain, flags, and SHA-256 of every output; the
# user_linux test verifies the hashes before running anything.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

zig_version="$(zig version)"
if [[ "$zig_version" != "0.16.0" ]]; then
    echo "error: Zig 0.16.0 is required (found $zig_version)" >&2
    exit 1
fi

targets=(x86_64-linux-musl aarch64-linux-musl riscv64-linux-musl)
programs=(hello fileio memory mman process signals timers hostsig threads threadexit exec fork events epoll sockets sockmsg shmem memfd pidfd fdinfo nodes xattr misc locks netlink ifreq sysvshm sysvsem sysvmsg seccomp inotify admin mqueue sched procmem kcmp iovec mlock mseal rseq aio splice ptrace ptracestops ptraceregs ptracejobs ptraceevents ptracefork ptraceseccomp ptraceblock stdin segv abort trap)
flags=(-static -Os -s -fno-sanitize=all -fno-stack-protector -ffile-prefix-map="$here"=.)

manifest="manifest.toml"
{
    echo "# Generated by build.sh; do not edit."
    echo "toolchain = \"zig $zig_version\""
    # The prefix map names this directory; record it location-independently.
    recorded="${flags[*]}"
    printf 'flags = "%s"\n' "${recorded//$here/<fixture-dir>}"
    echo
} > "$manifest"

for target in "${targets[@]}"; do
    arch="${target%%-*}"
    mkdir -p "bin/$arch"
    for prog in "${programs[@]}"; do
        out="bin/$arch/$prog"
        zig cc -target "$target" "${flags[@]}" -o "$out" "src/$prog.c"
        sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
        {
            echo "[[fixture]]"
            echo "path = \"$out\""
            echo "source = \"src/$prog.c\""
            echo "target = \"$target\""
            echo "sha256 = \"$sum\""
            echo
        } >> "$manifest"
    done
done

# i386 (x86-linux-musl) builds of the programs whose cases run as
# compatibility tasks so far; the rest need calls without a 32-bit
# conversion yet (threads, sockets, System V IPC, AIO, ptrace) or have
# 64-bit-only code. sigframes is an i386-only program (its case is in
# cases-i386.txt). Their expected results come from a real x86-64 kernel
# (oracle/record-kernel.sh), not from Docker.
i386_programs=(hello fileio memory mman memfd nodes signals shmem locks stdin segv abort trap sigframes)
mkdir -p bin/i386
for prog in "${i386_programs[@]}"; do
    out="bin/i386/$prog"
    zig cc -target x86-linux-musl "${flags[@]}" -o "$out" "src/$prog.c"
    sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
    {
        echo "[[fixture]]"
        echo "path = \"$out\""
        echo "source = \"src/$prog.c\""
        echo "target = \"x86-linux-musl\""
        echo "sha256 = \"$sum\""
        echo
    } >> "$manifest"
done
echo "built ${#targets[@]} targets x ${#programs[@]} programs, and ${#i386_programs[@]} i386 programs"
