#!/usr/bin/env bash
# Rebuilds the rax-user Linux fixtures from src/ and rewrites manifest.toml.
#
# Requirements: Zig 0.16.0 (its bundled musl and clang provide the Linux
# cross toolchains). Run from anywhere:
#
#     tests/fixtures/user/linux/build.sh
#
# Binaries are static, stripped, position-dependent executables (i386 and
# ARM EABI for subsets, listed below). The
# manifest records the toolchain, flags, and SHA-256 of every output; the
# user_linux test verifies the hashes before running anything.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

zig_version="$(zig version)"
if [[ "$zig_version" != "0.16.0" ]]; then
    echo "error: Zig 0.16.0 is required (found $zig_version)" >&2
    exit 1
fi

targets=(x86_64-linux-musl aarch64-linux-musl riscv64-linux-musl)
programs=(hello fileio memory mman process signals timers hostsig threads threadexit exec fork events epoll sockets sockmsg shmem memfd pidfd fdinfo nodes xattr misc locks netlink ifreq sysvshm sysvsem sysvmsg seccomp inotify admin mqueue sched procmem kcmp iovec mlock mseal rseq aio splice sendfault ptrace ptracestops ptraceregs ptracejobs ptraceevents ptracefork ptraceseccomp ptraceblock stdin segv abort trap)
flags=(-static -Os -s -fno-sanitize=all -fno-stack-protector -ffile-prefix-map="$here"=.)

manifest="manifest.toml"
{
    echo "# Generated by build.sh; do not edit."
    echo "toolchain = \"zig $zig_version\""
    # The prefix map names this directory; record it location-independently.
    recorded="${flags[*]}"
    printf 'flags = "%s"\n' "${recorded//$here/<fixture-dir>}"
    echo
} > "$manifest"

for target in "${targets[@]}"; do
    arch="${target%%-*}"
    mkdir -p "bin/$arch"
    for prog in "${programs[@]}"; do
        out="bin/$arch/$prog"
        zig cc -target "$target" "${flags[@]}" -o "$out" "src/$prog.c"
        sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
        {
            echo "[[fixture]]"
            echo "path = \"$out\""
            echo "source = \"src/$prog.c\""
            echo "target = \"$target\""
            echo "sha256 = \"$sum\""
            echo
        } >> "$manifest"
    done
done

# i386 (x86-linux-musl) builds of the programs whose cases run as
# compatibility tasks. The rest have 64-bit-only code (iovec's `1UL << 62`
# lengths and kernel addresses; ptrace, ptracestops, and ptraceregs do not
# build for i386), take a branch meant for another architecture
# (ptraceblock's i386 build assumes no block stepping, and its next check
# then races the resumed tracee), or check behavior the oracle kernel's
# configuration changes: sockets (its HZ=250 rounds socket timeouts up to
# 4 ms jiffies) and fdinfo (its timerfd check races on the emulated
# machine). sigframes, futex32, ipc32, mq32, aio32, select32, seccomp32, and
# ptrace32 are i386-only programs (their cases are in cases-i386.txt). Their
# expected results come from a real x86-64 kernel (oracle/record-kernel.sh),
# not from Docker.
i386_programs=(hello fileio memory mman memfd nodes signals shmem locks threads threadexit exec fork sched procmem stdin segv abort trap epoll sockmsg pidfd xattr misc netlink ifreq inotify splice sendfault mlock mseal sysvshm sysvsem sysvmsg mqueue aio ptracejobs ptraceevents ptracefork ptraceseccomp sigframes futex32 ipc32 mq32 aio32 select32 seccomp32 ptrace32)
mkdir -p bin/i386
for prog in "${i386_programs[@]}"; do
    out="bin/i386/$prog"
    zig cc -target x86-linux-musl "${flags[@]}" -o "$out" "src/$prog.c"
    sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
    {
        echo "[[fixture]]"
        echo "path = \"$out\""
        echo "source = \"src/$prog.c\""
        echo "target = \"x86-linux-musl\""
        echo "sha256 = \"$sum\""
        echo
    } >> "$manifest"
done

# ARM EABI (hard-float) builds, run as an arm64 kernel's compatibility
# tasks. -mcpu=cortex_a9-neon-d32 is an ARMv7-A core with VFPv3-D16 and no
# Advanced SIMD: code the emulated core runs completely (Zig's generic ARM
# CPU vectorizes with Advanced SIMD). Left out: iovec (64-bit-only code,
# as for i386); rseq (Linux
# 6.19's arm64 entry code never notes an interrupt from user mode, so the
# oracle aborts no critical section; later kernels do); and admin, sockets,
# and fdinfo (the oracle kernel's configuration: no modules and HZ=250; the
# timerfd check races on the emulated machine). Their expected results come
# from a real arm64 kernel (oracle/record-kernel.sh ... arm64).
arm_target=arm-linux-musleabihf
arm_cpu=cortex_a9-neon-d32
arm_programs=(hello fileio memory mman process signals timers threads threadexit exec fork events epoll sockmsg shmem memfd pidfd nodes xattr misc locks netlink ifreq sysvshm sysvsem sysvmsg seccomp inotify mqueue sched procmem kcmp mlock mseal aio splice sendfault ptrace ptracestops ptraceregs ptracejobs ptraceevents ptracefork ptraceseccomp ptraceblock stdin segv abort trap)
mkdir -p bin/arm
for prog in "${arm_programs[@]}"; do
    out="bin/arm/$prog"
    zig cc -target "$arm_target" -mcpu="$arm_cpu" "${flags[@]}" -o "$out" "src/$prog.c"
    sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
    {
        echo "[[fixture]]"
        echo "path = \"$out\""
        echo "source = \"src/$prog.c\""
        echo "target = \"$arm_target\""
        echo "cpu = \"$arm_cpu\""
        echo "sha256 = \"$sum\""
        echo
    } >> "$manifest"
done

# ARM-only programs (their cases are in cases-arm.txt): armframes, the
# AArch32 signal frames and 32-bit signal calls.
arm_only_programs=(armframes)
for prog in "${arm_only_programs[@]}"; do
    out="bin/arm/$prog"
    zig cc -target "$arm_target" -mcpu="$arm_cpu" "${flags[@]}" -o "$out" "src/$prog.c"
    sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
    {
        echo "[[fixture]]"
        echo "path = \"$out\""
        echo "source = \"src/$prog.c\""
        echo "target = \"$arm_target\""
        echo "cpu = \"$arm_cpu\""
        echo "sha256 = \"$sum\""
        echo
    } >> "$manifest"
done
echo "built ${#targets[@]} targets x ${#programs[@]} programs, ${#i386_programs[@]} i386 programs, and $((${#arm_programs[@]} + ${#arm_only_programs[@]})) ARM programs"
