#include <windows.h>
#include <winternl.h>
#include <cstdio>
#include <cstring>
#include <initializer_list>
#include <string>
// Read-only opens/queries of one existing system NLS key. No writes,
// creates, deletes, enumeration of personal data, or privilege changes.
using Open=LONG(NTAPI*)(HANDLE*,ACCESS_MASK,OBJECT_ATTRIBUTES*);
using Query=LONG(NTAPI*)(HANDLE,UNICODE_STRING*,ULONG,void*,ULONG,ULONG*);
using Close=LONG(NTAPI*)(HANDLE);
UNICODE_STRING us(const wchar_t* s){UNICODE_STRING u{};u.Length=USHORT(wcslen(s)*2);u.MaximumLength=u.Length+2;u.Buffer=const_cast<wchar_t*>(s);return u;}
int main(){setvbuf(stdout,nullptr,_IONBF,0);auto n=GetModuleHandleW(L"ntdll.dll");auto open=reinterpret_cast<Open>(GetProcAddress(n,"NtOpenKey"));auto query=reinterpret_cast<Query>(GetProcAddress(n,"NtQueryValueKey"));auto close=reinterpret_cast<Close>(GetProcAddress(n,"NtClose"));printf("pointer=%zu open=%u query=%u ACP=%u OEMCP=%u\n",sizeof(void*),unsigned(open!=nullptr),unsigned(query!=nullptr),GetACP(),GetOEMCP());if(!open||!query||!close)return 1;
 auto name=us(L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Nls\\CodePage");OBJECT_ATTRIBUTES a{};a.Length=sizeof(a);a.ObjectName=&name;a.Attributes=0x240;HANDLE key=nullptr;auto status=open(&key,GENERIC_READ,&a);printf("open normal status=%08lX handle=%p attributes_size=%lu\n",status,key,a.Length);if(status<0)return 2;
 auto p=static_cast<unsigned char*>(VirtualAlloc(nullptr,8192,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE));DWORD old;if(!p)return 3;
 for(auto text:{L"ACP",L"OEMCP",L"MACCP",L"1252",L"437",L"10000",L"65001",L"aCp",L"missing-rax-value"}){auto value=us(text);for(ULONG cls:{0u,1u,2u,3u,4u,5u,0xFFFFFFFFu})for(ULONG length:{0u,1u,4u,7u,8u,11u,12u,13u,16u,19u,20u,21u,22u,23u,24u,32u,64u,128u}){memset(p,0xA5,8192);ULONG returned=0xA5A5A5A5;auto s=query(key,&value,cls,p,length,&returned);printf("query pointer=%zu name=%ls class=%lu length=%lu status=%08lX returned=%08lX bytes=",sizeof(void*),text,cls,length,s,returned);for(unsigned i=0;i<64;++i)printf("%02X",p[i]);printf("\n");}}
 for(unsigned role=0;role<28;++role){VirtualProtect(p,8192,PAGE_READWRITE,&old);memset(p,0xA5,8192);auto value=us(L"ACP");UNICODE_STRING* vn=&value;auto output=static_cast<void*>(p);auto ret=reinterpret_cast<ULONG*>(p+4096);ULONG length=64,cls=2;HANDLE current=key;
 switch(role){case 0:ret=nullptr;break;case 1:ret=reinterpret_cast<ULONG*>(1);break;case 2:ret=reinterpret_cast<ULONG*>(p+4097);break;case 3:output=nullptr;break;case 4:output=p+1;break;case 5:VirtualProtect(p,4096,PAGE_READONLY,&old);break;case 6:VirtualProtect(p,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 7:VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 8:current=nullptr;vn=nullptr;break;case 9:current=nullptr;break;case 10:vn=nullptr;break;case 11:cls=5;ret=nullptr;break;case 12:length=0;output=nullptr;break;case 13:output=p+4080;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);ret=reinterpret_cast<ULONG*>(p+128);break;case 14:ret=reinterpret_cast<ULONG*>(p);break;case 15:current=reinterpret_cast<HANDLE>(LONG_PTR(-1));break;case 16:output=p+4072;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);ret=reinterpret_cast<ULONG*>(p+128);break;case 17:VirtualProtect(p,4096,PAGE_READONLY,&old);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 18:VirtualProtect(p,4096,PAGE_READWRITE|PAGE_GUARD,&old);VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 19:current=nullptr;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 20:current=nullptr;output=p+1;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 21:cls=5;VirtualProtect(p,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 22:length=0;output=p+1;break;case 23:current=nullptr;memcpy(p,&value,sizeof(value));vn=reinterpret_cast<UNICODE_STRING*>(p);VirtualProtect(p,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 24:current=nullptr;cls=5;break;case 25:vn=nullptr;cls=5;break;case 26:output=p+1;ret=nullptr;break;case 27:length=12;VirtualProtect(p,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;}
 auto s=query(current,vn,cls,output,length,ret);MEMORY_BASIC_INFORMATION b{},c{};VirtualQuery(p,&b,sizeof(b));VirtualQuery(p+4096,&c,sizeof(c));VirtualProtect(p,8192,PAGE_READWRITE,&old);printf("query pointer=%zu role=%u class=%lu length=%lu status=%08lX output_protect=%08lX returned_protect=%08lX returned=%08lX bytes=",sizeof(void*),role,cls,length,s,b.Protect,c.Protect,*reinterpret_cast<ULONG*>(p+4096));for(unsigned i=0;i<32;++i)printf("%02X",p[i]);auto rb=reinterpret_cast<ULONG_PTR>(ret),ob=reinterpret_cast<ULONG_PTR>(output),pb=reinterpret_cast<ULONG_PTR>(p);if(rb>=pb&&rb<=pb+8192-4){ULONG actual;memcpy(&actual,ret,4);printf(" actual_returned=%08lX",actual);}else printf(" actual_returned=unreadable");printf(" selected_bytes=");if(ob>=pb&&ob<=pb+8192-32)for(unsigned i=0;i<32;++i)printf("%02X",static_cast<unsigned char*>(output)[i]);else printf("unreadable");printf("\n");}
 for(ACCESS_MASK access:{0u,1u,8u,0x20019u,0x80000000u,0x2000000u,0x20019u|0x100u,0x20019u|0x200u}){HANDLE h=nullptr;auto s=open(&h,access,&a);printf("open pointer=%zu access=%08lX status=%08lX handle=%p\n",sizeof(void*),access,s,h);if(s>=0)close(h);}
 for(unsigned role=0;role<22;++role){VirtualProtect(p,8192,PAGE_READWRITE,&old);memset(p,0xA5,8192);auto attrs=a;OBJECT_ATTRIBUTES* ap=&attrs;auto output=reinterpret_cast<HANDLE*>(p);auto nm=name;ACCESS_MASK access=GENERIC_READ;
 switch(role){case 0:output=nullptr;break;case 1:output=reinterpret_cast<HANDLE*>(1);break;case 2:output=reinterpret_cast<HANDLE*>(p+1);break;case 3:ap=nullptr;break;case 4:attrs.Length=0;break;case 5:attrs.ObjectName=nullptr;break;case 6:attrs.Attributes=0;break;case 7:attrs.Attributes=0xFFFFFFFF;break;case 8:VirtualProtect(p,4096,PAGE_READONLY,&old);break;case 9:VirtualProtect(p,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 10:nm.Buffer=nullptr;attrs.ObjectName=&nm;break;case 11:attrs.RootDirectory=key;attrs.ObjectName=&nm;break;case 12:nm=us(L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Nls\\missing-rax-key");attrs.ObjectName=&nm;break;case 13:access=0xFFFFFFFF;break;case 14:attrs.SecurityDescriptor=reinterpret_cast<void*>(1);break;case 15:attrs.SecurityQualityOfService=reinterpret_cast<void*>(1);break;case 16:attrs.RootDirectory=reinterpret_cast<HANDLE>(1);break;case 17:nm.Length=1;attrs.ObjectName=&nm;break;case 18:nm.MaximumLength=0;attrs.ObjectName=&nm;break;case 19:ap=reinterpret_cast<OBJECT_ATTRIBUTES*>(p+4096);memcpy(ap,&a,sizeof(a));VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 20:ap=reinterpret_cast<OBJECT_ATTRIBUTES*>(p+4096);memcpy(ap,&a,sizeof(a));VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);output=nullptr;break;case 21:ap=reinterpret_cast<OBJECT_ATTRIBUTES*>(p+4097);memcpy(ap,&a,sizeof(a));break;}
 auto s=open(output,access,ap);MEMORY_BASIC_INFORMATION b{};VirtualQuery(p,&b,sizeof(b));VirtualProtect(p,8192,PAGE_READWRITE,&old);printf("open pointer=%zu role=%u status=%08lX output_protect=%08lX bytes=",sizeof(void*),role,s,b.Protect);for(unsigned i=0;i<16;++i)printf("%02X",p[i]);printf("\n");if(s>=0){HANDLE h;memcpy(&h,output,sizeof(h));close(h);}}
 close(key);VirtualFree(p,0,MEM_RELEASE);}
