#!/usr/bin/env bash
# Generated artifacts only; custom entry, not ordinary CRT startup.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository="$(cd "$fixture_dir/../../../../.." && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-crt-onexit.XXXXXX")"
programs=(basic mutation nested repair terminal oom)
cleanup() {
    for program in "${programs[@]}" companion; do rm -f "$task_dir/$program.obj"; done
    for group in kernel32 runtime heap string discard; do
        rm -f "$task_dir/$group.lib" "$task_dir/$group.exp"
    done
    rmdir "$task_dir"
}
trap cleanup EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
zig_bin="${ZIG_BIN:-zig}"
[[ "$("$zig_bin" version)" == 0.16.0 ]] || { echo 'Expected Zig 0.16.0 provenance' >&2; exit 1; }
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=. -ffile-prefix-map="$repository"=repository)
cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; suffix=-x86; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; suffix=; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; suffix=; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    "$dlltool_bin" -m "$dllmachine" -k -d "src/kernel32$suffix.def" -l "$task_dir/kernel32.lib"
    for binding in ucrtbase apiset; do
        for group in runtime heap string; do
            if [[ "$binding" == apiset ]]; then dll="api-ms-win-crt-$group-l1-1-0.dll"; else dll=ucrtbase.dll; fi
            "$dlltool_bin" -m "$dllmachine" -D "$dll" -d "src/$group.def" -l "$task_dir/$group.lib"
        done
        for program in "${programs[@]}"; do
            mkdir -p "bin/$arch/$binding"
            "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" \
                -c "src/$program.c" -o "$task_dir/$program.obj"
            "$link_bin" /machine:"$machine" /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
                /entry:entry /subsystem:console /stack:1048576,4096 /heap:1048576,4096 \
                /implib:"$task_dir/discard.lib" /out:"bin/$arch/$binding/$program.exe" \
                "$task_dir/$program.obj" "$task_dir/kernel32.lib" "$task_dir/runtime.lib" \
                "$task_dir/heap.lib" "$task_dir/string.lib"
        done
        dll_entry=DllMain
        if [[ "$arch" == x86 ]]; then dll_entry=DllMain@12; fi
        "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" \
            -c src/companion.c -o "$task_dir/companion.obj"
        "$link_bin" /machine:"$machine" /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
            /dll /entry:"$dll_entry" /def:src/companion.def /subsystem:console \
            /implib:"$task_dir/discard.lib" /out:"bin/$arch/$binding/onexit.dll" \
            "$task_dir/companion.obj" "$task_dir/kernel32.lib" "$task_dir/runtime.lib"
    done
done
{
    printf '# Generated by crt_onexit/build.sh; no native Windows oracle.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'zig = "%s"\n' "$("$zig_bin" version)"
    for tool in clang linker dlltool zig; do
        case "$tool" in clang) executable="$clang_bin";; linker) executable="$link_bin";; dlltool) executable="$dlltool_bin";; zig) executable="$zig_bin";; esac
        printf '%s_sha256 = "%s"\n' "$tool" "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    printf 'oracle = "Primary table lifecycle plus genuine named bindings and explicit detached-generation/ownership/fault/heap profiles; custom entry, not ordinary startup"\n'
    for source in build.sh baseline.sh README.md src/*.c src/*.h src/*.def ../layout/public.c \
        ../../../../../docs/specifications/windows/crt-initializers/mingw14/corecrt-startup-excerpt.h \
        ../../../../../docs/specifications/windows/crt-initializers/zig/corecrt-startup-excerpt.h \
        ../../../../../docs/specifications/windows/crt-startup/mingw14/winnt-exception-context-excerpt.h \
        ../../../../../docs/specifications/windows/crt-startup/zig/winnt-exception-context-excerpt.h; do
        printf '\n[[source]]\npath = "%s"\n' "$source"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    for arch in x86 x64 arm64; do
        for binding in ucrtbase apiset; do
            for program in "${programs[@]}"; do
                printf '\n[[fixture]]\narch = "%s"\nbinding = "%s"\nprogram = "%s"\npath = "bin/%s/%s/%s.exe"\n' \
                    "$arch" "$binding" "$program" "$arch" "$binding" "$program"
                printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/$binding/$program.exe" | cut -d' ' -f1)"
                printf 'bytes = %s\nexpected_exit = 0\nrole = "executable"\n' "$(wc -c < "bin/$arch/$binding/$program.exe" | tr -d ' ')"
            done
            printf '\n[[fixture]]\narch = "%s"\nbinding = "%s"\nprogram = "companion"\npath = "bin/%s/%s/onexit.dll"\n' \
                "$arch" "$binding" "$arch" "$binding"
            printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/$binding/onexit.dll" | cut -d' ' -f1)"
            printf 'bytes = %s\nrole = "dependency"\n' "$(wc -c < "bin/$arch/$binding/onexit.dll" | tr -d ' ')"
        done
    done
} > manifest.toml
