#!/usr/bin/env bash
# Reproducible custom-entry argv/environment probes, not ordinary CRT startup.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository="$(cd "$fixture_dir/../../../../.." && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-crt-startup.XXXXXX")"
programs=(arguments environment wildcards newmode modes isolation)
cleanup() {
    for program in "${programs[@]}" narrow wide; do rm -f "$task_dir/$program.obj"; done
    for group in kernel32 runtime environment heap env accessors discard; do
        rm -f "$task_dir/$group.lib" "$task_dir/$group.exp"
    done
    rmdir "$task_dir"
}
trap cleanup EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
zig_bin="${ZIG_BIN:-zig}"
[[ "$("$zig_bin" version)" == 0.16.0 ]] || { echo 'Expected installed Zig 0.16.0 provenance' >&2; exit 1; }
wrapper_base="$repository/docs/specifications/windows/crt-initializers/zig"
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=. -ffile-prefix-map="$repository"=repository)
cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; suffix=-x86; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; suffix=; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; suffix=; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    "$dlltool_bin" -m "$dllmachine" -k -d "src/kernel32$suffix.def" -l "$task_dir/kernel32.lib"
    for pair in 'narrow getmainargs' 'wide wgetmainargs'; do
        read -r object wrapper <<< "$pair"
        "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" \
            -I src/wrapper-headers -c "$wrapper_base/ucrt__$wrapper.c" -o "$task_dir/$object.obj"
    done
    for binding in msvcrt ucrtbase apiset; do
        if [[ "$binding" == msvcrt ]]; then
            define=(-DLEGACY_CRT)
            "$dlltool_bin" -m "$dllmachine" -D msvcrt.dll -d src/legacy-runtime.def -l "$task_dir/runtime.lib"
            legacy_new=src/legacy-new.def
            if [[ "$arch" == arm64 ]]; then legacy_new=src/legacy-new-arm64.def; fi
            "$dlltool_bin" -m "$dllmachine" -D msvcrt.dll -d "$legacy_new" -l "$task_dir/heap.lib"
            libraries=("$task_dir/kernel32.lib" "$task_dir/runtime.lib" "$task_dir/heap.lib")
            if [[ "$arch" != arm64 ]]; then
                "$dlltool_bin" -m "$dllmachine" -D msvcrt.dll -d src/legacy-env.def -l "$task_dir/env.lib"
                libraries+=("$task_dir/env.lib")
            else
                "$dlltool_bin" -m "$dllmachine" -D msvcrt.dll -d src/legacy-env-arm64.def -l "$task_dir/env.lib"
                libraries+=("$task_dir/env.lib")
            fi
            if [[ "$arch" == x86 ]]; then
                "$dlltool_bin" -m "$dllmachine" -D msvcrt.dll -d src/legacy-accessors-x86.def -l "$task_dir/accessors.lib"
                libraries+=("$task_dir/accessors.lib")
            fi
        else
            define=()
            for group in runtime environment heap; do
                if [[ "$binding" == apiset ]]; then dll="api-ms-win-crt-$group-l1-1-0.dll"; else dll=ucrtbase.dll; fi
                "$dlltool_bin" -m "$dllmachine" -D "$dll" -d "src/$group.def" -l "$task_dir/$group.lib"
            done
            libraries=("$task_dir/kernel32.lib" "$task_dir/runtime.lib" "$task_dir/environment.lib" "$task_dir/heap.lib")
        fi
        for program in "${programs[@]}"; do
            if [[ "$program" == modes && "$binding" == msvcrt ]]; then continue; fi
            if [[ "$program" == isolation && "$binding" != ucrtbase ]]; then continue; fi
            mkdir -p "bin/$arch/$binding"
            "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" "${define[@]}" \
                -c "src/$program.c" -o "$task_dir/$program.obj"
            wrappers=()
            if [[ "$binding" != msvcrt && "$program" != modes && "$program" != isolation ]]; then
                wrappers=("$task_dir/narrow.obj" "$task_dir/wide.obj")
            fi
            "$link_bin" /machine:"$machine" /nodefaultlib /timestamp:0 /dynamicbase /nxcompat \
                /entry:entry /subsystem:console /stack:1048576,4096 /heap:1048576,4096 \
                /implib:"$task_dir/discard.lib" /out:"bin/$arch/$binding/$program.exe" \
                "$task_dir/$program.obj" "${wrappers[@]}" "${libraries[@]}"
        done
    done
done
{
    printf '# Generated by crt_startup/build.sh; no native Windows oracle.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'zig = "%s"\n' "$("$zig_bin" version)"
    for tool in clang linker dlltool zig; do
        case "$tool" in clang) executable="$clang_bin";; linker) executable="$link_bin";; dlltool) executable="$dlltool_bin";; zig) executable="$zig_bin";; esac
        printf '%s_sha256 = "%s"\n' "$tool" "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    printf 'oracle = "Primary CRT argv/environment contracts plus named admission and explicitly retained parsing/enumeration profiles; custom entry, not ordinary compiler startup"\n'
    for source in build.sh baseline.sh README.md src/*.c src/*.h src/*.def src/wrapper-headers/*.h ../layout/public.c \
        ../../../../../docs/specifications/windows/crt-initializers/zig/ucrt__getmainargs.c \
        ../../../../../docs/specifications/windows/crt-initializers/zig/ucrt__wgetmainargs.c; do
        printf '\n[[source]]\npath = "%s"\n' "$source"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    for arch in x86 x64 arm64; do
        for binding in msvcrt ucrtbase apiset; do
            for program in "${programs[@]}"; do
                if [[ "$program" == modes && "$binding" == msvcrt ]]; then continue; fi
                if [[ "$program" == isolation && "$binding" != ucrtbase ]]; then continue; fi
                printf '\n[[fixture]]\narch = "%s"\nbinding = "%s"\nprogram = "%s"\npath = "bin/%s/%s/%s.exe"\n' \
                    "$arch" "$binding" "$program" "$arch" "$binding" "$program"
                printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/$binding/$program.exe" | cut -d' ' -f1)"
                printf 'bytes = %s\nexpected_exit = 0\n' "$(wc -c < "bin/$arch/$binding/$program.exe" | tr -d ' ')"
            done
        done
    done
} > manifest.toml
