#!/usr/bin/env python3
"""Generate RAX's Linux system-call number and errno tables.

Reads the Linux 6.19 UAPI headers vendored under
docs/specifications/linux/uapi-6.19 (see uapi-6.19.provenance.md) and writes
src/user/linux/abi/syscalls.rs and src/user/linux/abi/errno_table.rs. The
output is checked in; rerun this script after importing a newer header set
and review the diff:

    python3 tools/linux/gen_syscalls.py

`tests/suites/user/linux_abi_tables.rs` re-parses the same headers and fails
if the checked-in tables disagree with them.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
UAPI = os.path.join(ROOT, "docs", "specifications", "linux", "uapi-6.19")
OUT = os.path.join(ROOT, "src", "user", "linux", "abi", "syscalls.rs")
ERRNO_OUT = os.path.join(ROOT, "src", "user", "linux", "abi", "errno_table.rs")
ERRNO_HEADERS = [
    "any-linux-any/asm-generic/errno-base.h",
    "any-linux-any/asm-generic/errno.h",
]
ERRNO_DEFINE = re.compile(r"^#define\s+(E[A-Z0-9]+)\s+(\d+)\b")
ERRNO_ALIAS = re.compile(r"^#define\s+(E[A-Z0-9]+)\s+(E[A-Z0-9]+)\b")

# (Rust function suffix, header path, doc label)
TABLES = [
    ("x86_64", "x86-linux-any/asm/unistd_64.h", "x86-64 (`arch/x86/entry/syscalls/syscall_64.tbl`, common + 64)"),
    ("aarch64", "aarch64-linux-any/asm/unistd_64.h", "AArch64 (asm-generic numbering)"),
    ("riscv64", "riscv-linux-any/asm/unistd_64.h", "RV64 (asm-generic numbering plus RISC-V calls)"),
    ("i386", "x86-linux-any/asm/unistd_32.h", "i386 (`arch/x86/entry/syscalls/syscall_32.tbl`, the `int $0x80` table)"),
]

DEFINE = re.compile(r"^#define __NR_(\w+)\s+(\d+)\s*$")


def parse(path):
    table = []
    with open(os.path.join(UAPI, path)) as f:
        for line in f:
            m = DEFINE.match(line)
            if m:
                table.append((m.group(1), int(m.group(2))))
    if not table:
        sys.exit(f"no syscall definitions in {path}")
    nums = [n for _, n in table]
    if len(set(nums)) != len(nums):
        sys.exit(f"duplicate syscall numbers in {path}")
    return table


def variant(name):
    parts = [p for p in name.split("_") if p]
    out = "".join(p[:1].upper() + p[1:] for p in parts)
    if out[0].isdigit():
        out = "N" + out
    return out


def main():
    tables = [(arch, parse(path), label) for arch, path, label in TABLES]
    names = sorted({n for _, t, _ in tables for n, _ in t})
    variants = {n: variant(n) for n in names}
    if len(set(variants.values())) != len(variants):
        sys.exit("variant name collision")

    w = []
    w.append("// @generated by tools/linux/gen_syscalls.py from the Linux 6.19 UAPI")
    w.append("// headers in docs/specifications/linux/uapi-6.19. Do not edit by hand.")
    w.append("")
    w.append("//! Linux system-call identities and per-ABI numbering.")
    w.append("")
    w.append("/// A Linux system call, independent of any ABI's numbering.")
    w.append("///")
    w.append(f"/// The set is the union of the {len(names)} calls defined by the supported ABIs.")
    w.append("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]")
    w.append("pub enum Sysno {")
    for n in names:
        w.append(f"    /// `{n}`")
        w.append(f"    {variants[n]},")
    w.append("}")
    w.append("")
    w.append("impl Sysno {")
    w.append("    /// Every known system call, sorted by name.")
    w.append("    pub const ALL: &'static [Sysno] = &[")
    for n in names:
        w.append(f"        Sysno::{variants[n]},")
    w.append("    ];")
    w.append("")
    w.append("    /// The kernel's name for the call (without the `sys_` prefix).")
    w.append("    pub const fn name(self) -> &'static str {")
    w.append("        match self {")
    for n in names:
        w.append(f"            Sysno::{variants[n]} => \"{n}\",")
    w.append("        }")
    w.append("    }")
    w.append("}")
    for arch, table, label in tables:
        w.append("")
        w.append(f"/// {label}: the call with number `nr`.")
        w.append(f"pub const fn {arch}_sysno(nr: u64) -> Option<Sysno> {{")
        w.append("    Some(match nr {")
        for n, num in sorted(table, key=lambda x: x[1]):
            w.append(f"        {num} => Sysno::{variants[n]},")
        w.append("        _ => return None,")
        w.append("    })")
        w.append("}")
        w.append("")
        w.append(f"/// {label}: every `(number, call)` pair in ascending number order.")
        w.append(f"pub const {arch.upper()}_TABLE: &[(u64, Sysno)] = &[")
        for n, num in sorted(table, key=lambda x: x[1]):
            w.append(f"    ({num}, Sysno::{variants[n]}),")
        w.append("];")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(w) + "\n")
    print(f"wrote {OUT}: {len(names)} calls")
    gen_errno()


def gen_errno():
    values = []
    aliases = []
    for path in ERRNO_HEADERS:
        with open(os.path.join(UAPI, path)) as f:
            for line in f:
                m = ERRNO_DEFINE.match(line)
                if m:
                    values.append((m.group(1), int(m.group(2))))
                    continue
                m = ERRNO_ALIAS.match(line)
                if m:
                    aliases.append((m.group(1), m.group(2)))
    nums = [n for _, n in values]
    if len(set(nums)) != len(nums):
        sys.exit("duplicate errno values")
    known = dict(values)
    w = []
    w.append("// @generated by tools/linux/gen_syscalls.py from the Linux 6.19 UAPI")
    w.append("// headers in docs/specifications/linux/uapi-6.19. Do not edit by hand.")
    w.append("")
    w.append("//! Linux `errno` values (`asm-generic/errno-base.h`, `asm-generic/errno.h`),")
    w.append("//! shared by every supported ABI.")
    w.append("")
    for name, num in values:
        w.append(f"/// `{name}`")
        w.append(f"pub const {name}: i32 = {num};")
    for name, target in aliases:
        if target not in known:
            sys.exit(f"alias {name} -> unknown {target}")
        w.append(f"/// `{name}` (alias of `{target}`)")
        w.append(f"pub const {name}: i32 = {target};")
    w.append("")
    w.append("/// The canonical name of a Linux errno value.")
    w.append("pub const fn errno_name(errno: i32) -> Option<&'static str> {")
    w.append("    Some(match errno {")
    for name, num in values:
        w.append(f"        {num} => \"{name}\",")
    w.append("        _ => return None,")
    w.append("    })")
    w.append("}")
    w.append("")
    w.append("/// Every `(name, value)` pair, including aliases, in header order.")
    w.append("pub const ERRNO_TABLE: &[(&str, i32)] = &[")
    for name, num in values:
        w.append(f"    (\"{name}\", {num}),")
    for name, target in aliases:
        w.append(f"    (\"{name}\", {known[target]}),")
    w.append("];")
    with open(ERRNO_OUT, "w") as f:
        f.write("\n".join(w) + "\n")
    print(f"wrote {ERRNO_OUT}: {len(values)} values, {len(aliases)} aliases")


if __name__ == "__main__":
    main()
