#include <windows.h>
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <initializer_list>
// Original read-only process-local oracle for native and WoW64 boundaries.
using Query=LONG(NTAPI*)(HANDLE,const void*,ULONG,void*,SIZE_T,SIZE_T*);
static Query query;
static LONG invoke(HANDLE h,const void* a,ULONG k,void* o,SIZE_T n,SIZE_T* r,ULONG* e){__try{return query(h,a,k,o,n,r);}__except(EXCEPTION_EXECUTE_HANDLER){*e=GetExceptionCode();return LONG(*e);}}
static void row(const char* group,unsigned role,ULONG kind,HANDLE h,const void* address,void* out,SIZE_T size,SIZE_T* returned,unsigned char* p){ULONG ex=0;auto status=invoke(h,address,kind,out,size,returned,&ex);MEMORY_BASIC_INFORMATION a{},b{};VirtualQuery(p+4096,&a,sizeof(a));VirtualQuery(p+8192,&b,sizeof(b));printf("%s role=%u class=%lu length=%zu status=%08lX exception=%08lX guards=%u%u bytes=",group,role,kind,size,status,ex,unsigned((a.Protect&PAGE_GUARD)!=0),unsigned((b.Protect&PAGE_GUARD)!=0));for(unsigned i=128;i<192;i++)printf("%02X",p[i]);printf(" returned=");for(unsigned i=256;i<272;i++)printf("%02X",p[i]);printf("\n");}
int main(){setvbuf(stdout,nullptr,_IONBF,0);auto n=GetModuleHandleW(L"ntdll.dll");query=reinterpret_cast<Query>(GetProcAddress(n,"NtQueryVirtualMemory"));if(!query)return 1;auto p=static_cast<unsigned char*>(VirtualAlloc(nullptr,16384,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE));auto reserved=VirtualAlloc(nullptr,8192,MEM_RESERVE,PAGE_READWRITE);if(!p||!reserved)return 2;printf("pointer=%zu ntdll=%p main=%p private=%p reserved=%p\n",sizeof(void*),n,GetModuleHandleW(nullptr),p,reserved);DWORD old;
for(ULONG kind:{0u,6u})for(unsigned role=0;role<38;role++){VirtualProtect(p,16384,PAGE_READWRITE,&old);memset(p,0xa5,16384);HANDLE h=GetCurrentProcess();const void* address=n;void* out=p+128;SIZE_T size=kind==0?(sizeof(void*)==4?28:48):(sizeof(void*)==4?12:24);auto ret=reinterpret_cast<SIZE_T*>(p+256);
switch(role){case 1:out=p+132;break;case 2:out=p+130;break;case 3:out=p+4096-size;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);size+=8;break;case 4:out=p+4096-size;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);size+=8;break;case 5:out=nullptr;break;case 6:out=nullptr;h=nullptr;break;case 7:address=nullptr;break;case 8:address=reserved;break;case 9:address=reserved;out=nullptr;break;case 10:address=reinterpret_cast<void*>(~uintptr_t(0));break;case 11:address=reinterpret_cast<void*>(~uintptr_t(0));ret=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 12:address=nullptr;ret=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 13:address=nullptr;out=reinterpret_cast<void*>(uintptr_t(1));break;case 14:h=nullptr;out=p+4096;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 15:h=nullptr;ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 16:size=0;out=p+4096;ret=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+4096,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 17:out=p+4096;ret=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+4096,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 18:out=p+4096-size;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 19:ret=reinterpret_cast<SIZE_T*>(p+4096-sizeof(void*)+1);VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 20:address=p+4096;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 21:address=p+4096;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 22:ret=reinterpret_cast<SIZE_T*>(out);break;case 23:out=reinterpret_cast<void*>(uintptr_t(1));ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 24:out=nullptr;ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 25:address=nullptr;ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 26:address=reinterpret_cast<void*>(~uintptr_t(0));ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 27:h=nullptr;ret=reinterpret_cast<SIZE_T*>(p+4096);out=p+8192;VirtualProtect(p+4096,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 28:size=SIZE_T(~uintptr_t(0));break;case 29:size=sizeof(void*)==4?SIZE_T(0x80000000u):SIZE_T(0x100000000ull);break;case 30:address=reinterpret_cast<void*>(uintptr_t(1));break;case 31:address=GetModuleHandleW(nullptr);break;case 32:address=p+12288;break;case 33:address=reinterpret_cast<char*>(reserved)+4096;break;case 34:address=p+8192;ret=nullptr;break;case 35:out=p+4096-size+1;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 36:out=p+4096;ret=reinterpret_cast<SIZE_T*>(p+4160);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 37:out=p+4096;ret=reinterpret_cast<SIZE_T*>(out);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;}
row("boundary",role,kind,h,address,out,size,ret,p);}
for(ULONG kind:{0u,6u})for(DWORD access:{0u,0x10u,0x400u,0x1000u,0x1010u,0x410u,unsigned(PROCESS_ALL_ACCESS)}){VirtualProtect(p,16384,PAGE_READWRITE,&old);memset(p,0xa5,16384);HANDLE h=OpenProcess(access,FALSE,GetCurrentProcessId());printf("handle requested=%08lX opened=%u error=%lu\n",access,unsigned(h!=nullptr),h?0:GetLastError());if(h){row("rights",access,kind,h,n,p+128,64,reinterpret_cast<SIZE_T*>(p+256),p);CloseHandle(h);}}
for(ULONG kind=0;kind<24;kind++){memset(p,0xa5,4096);row("class",kind,kind,GetCurrentProcess(),n,p+128,128,reinterpret_cast<SIZE_T*>(p+256),p);}
for(ULONG kind:{0u,6u,0xffffffffu})for(unsigned role=0;role<6;role++){VirtualProtect(p,16384,PAGE_READWRITE,&old);memset(p,0xa5,16384);const void* address=role<4?reinterpret_cast<void*>(~uintptr_t(0)):n;void* out=role==1||role==3||role==5?reinterpret_cast<void*>(uintptr_t(1)):p+128;SIZE_T size=role==0||role==1||role==4||role==5?0:64;auto ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);row("priority",role,kind,GetCurrentProcess(),address,out,size,ret,p);}
VirtualFree(reserved,0,MEM_RELEASE);VirtualFree(p,0,MEM_RELEASE);return 0;}
