#include <windows.h>
#include <cstdio>
#include <cstring>
#include <initializer_list>
#include <cstdint>
// Original process-local read-only query oracle. No remote process, writes,
// image modifications, privilege changes or guest-to-host forwarding.
using Query=LONG(NTAPI*)(HANDLE,const void*,ULONG,void*,SIZE_T,SIZE_T*);
static Query query;
static LONG invoke(HANDLE process,const void* address,ULONG kind,void* out,SIZE_T size,SIZE_T* returned,ULONG* exception){__try{return query(process,address,kind,out,size,returned);}__except(EXCEPTION_EXECUTE_HANDLER){*exception=GetExceptionCode();return LONG(*exception);}}
int main(){setvbuf(stdout,nullptr,_IONBF,0);auto n=GetModuleHandleW(L"ntdll.dll");query=reinterpret_cast<Query>(GetProcAddress(n,"NtQueryVirtualMemory"));if(!query)return 1;auto main=GetModuleHandleW(nullptr);auto ns=reinterpret_cast<IMAGE_NT_HEADERS*>(reinterpret_cast<char*>(n)+reinterpret_cast<IMAGE_DOS_HEADER*>(n)->e_lfanew)->OptionalHeader.SizeOfImage;auto ms=reinterpret_cast<IMAGE_NT_HEADERS*>(reinterpret_cast<char*>(main)+reinterpret_cast<IMAGE_DOS_HEADER*>(main)->e_lfanew)->OptionalHeader.SizeOfImage;printf("pointer=%zu ntdll=%p main=%p ntdll-size=%lu main-size=%lu\n",sizeof(void*),n,main,ns,ms);auto p=static_cast<unsigned char*>(VirtualAlloc(nullptr,16384,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE));if(!p)return 2;DWORD old;
for(unsigned target=0;target<7;target++)for(ULONG kind:{0u,6u,0xffffffffu})for(SIZE_T size:{0u,1u,12u,16u,20u,24u,28u,32u,48u,64u,128u}){memset(p,0xa5,4096);const void* address=target==0?static_cast<const void*>(n):target==1?static_cast<const void*>(GetModuleHandleW(nullptr)):target==2?static_cast<const void*>(reinterpret_cast<const char*>(n)+1):target==3?static_cast<const void*>(p+8192):target==4?nullptr:target==5?reinterpret_cast<const void*>(uintptr_t(1)):reinterpret_cast<const void*>(~uintptr_t(0));SIZE_T returned=~SIZE_T(0);ULONG ex=0;auto status=invoke(GetCurrentProcess(),address,kind,p+128,size,&returned,&ex);printf("matrix target=%u class=%lu length=%zu status=%08lX exception=%08lX returned=%zu bytes=",target,kind,size,status,ex,returned);for(unsigned i=0;i<64;i++)printf("%02X",p[128+i]);printf("\n");}
for(unsigned role=0;role<30;role++){VirtualProtect(p,16384,PAGE_READWRITE,&old);memset(p,0xa5,16384);HANDLE process=GetCurrentProcess();const void* address=n;ULONG kind=6;void* out=p+128;SIZE_T size=sizeof(void*)==4?12:24;SIZE_T* returned=reinterpret_cast<SIZE_T*>(p+256);ULONG ex=0;
switch(role){case 1:returned=nullptr;break;case 2:out=nullptr;break;case 3:out=reinterpret_cast<void*>(uintptr_t(1));break;case 4:returned=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 5:out=p+129;break;case 6:returned=reinterpret_cast<SIZE_T*>(p+257);break;case 7:process=nullptr;break;case 8:process=reinterpret_cast<HANDLE>(intptr_t(-2));break;case 9:kind=0xffffffffu;out=reinterpret_cast<void*>(uintptr_t(1));break;case 10:kind=0xffffffffu;returned=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 11:size=0;out=reinterpret_cast<void*>(uintptr_t(1));break;case 12:size=0;returned=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 13:out=p+4096;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 14:returned=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 15:out=p+4096;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 16:returned=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 17:out=p+4096;returned=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+4096,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 18:process=nullptr;returned=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 19:address=p+12288;VirtualProtect(p+12288,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 20:address=p+12288;VirtualProtect(p+12288,4096,PAGE_NOACCESS,&old);break;case 21:address=p+12288;break;case 22:returned=reinterpret_cast<SIZE_T*>(out);break;case 23:out=p+4092;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 24:kind=0;size=sizeof(void*)==4?28:48;break;case 25:kind=0;size=1;break;case 26:kind=0;out=p+129;size=48;break;case 27:kind=0;returned=reinterpret_cast<SIZE_T*>(p+257);size=48;break;case 28:address=reinterpret_cast<const void*>(~uintptr_t(0));break;case 29:process=nullptr;out=nullptr;returned=nullptr;break;}
auto status=invoke(process,address,kind,out,size,returned,&ex);MEMORY_BASIC_INFORMATION a{},b{},c{};VirtualQuery(p+4096,&a,sizeof(a));VirtualQuery(p+8192,&b,sizeof(b));VirtualQuery(p+12288,&c,sizeof(c));printf("fault role=%u class=%lu length=%zu status=%08lX exception=%08lX guards=%u%u%u bytes=",role,kind,size,status,ex,unsigned((a.Protect&PAGE_GUARD)!=0),unsigned((b.Protect&PAGE_GUARD)!=0),unsigned((c.Protect&PAGE_GUARD)!=0));for(unsigned i=128;i<192;i++)printf("%02X",p[i]);printf(" returned=");for(unsigned i=256;i<272;i++)printf("%02X",p[i]);printf("\n");}VirtualFree(p,0,MEM_RELEASE);}
