#!/usr/bin/env bash
# Rebuild the freestanding x64 PE and record its source/tool/artifact digests.
set -euo pipefail

fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
work_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-dynamic-unwind-x64.XXXXXX")"
cleanup() {
    rm -f "$work_dir/probe.obj" "$work_dir/dynamic.obj" "$work_dir/kernel32.lib"
    rmdir "$work_dir"
}
trap cleanup EXIT

clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
readobj_bin="${LLVM_READOBJ_BIN:-llvm-readobj}"
nm_bin="${LLVM_NM_BIN:-llvm-nm}"
cd "$fixture_dir"
mkdir -p bin

"$dlltool_bin" -m i386:x86-64 -k -d src/kernel32.def -l "$work_dir/kernel32.lib"
"$clang_bin" --target=x86_64-pc-windows-msvc -Oz -ffreestanding -fno-builtin \
    -fno-stack-protector -fno-ident -fno-vectorize -fno-slp-vectorize \
    -ffile-prefix-map="$fixture_dir"=. -Wall -Wextra -Werror \
    -c src/probe.c -o "$work_dir/probe.obj"
"$clang_bin" --target=x86_64-pc-windows-msvc \
    -ffile-prefix-map="$fixture_dir"=. -c src/dynamic.S -o "$work_dir/dynamic.obj"
"$link_bin" /machine:x64 /entry:entry /subsystem:console /nodefaultlib \
    /timestamp:0 /dynamicbase /nxcompat /stack:1048576,4096 /heap:1048576,4096 \
    /out:bin/dynamic_unwind.exe \
    "$work_dir/probe.obj" "$work_dir/dynamic.obj" "$work_dir/kernel32.lib"

imports="$("$readobj_bin" --coff-imports bin/dynamic_unwind.exe)"
headers="$("$readobj_bin" --file-headers bin/dynamic_unwind.exe)"
symbols="$("$nm_bin" -f posix "$work_dir/dynamic.obj")"
[[ "$imports" == *"Name: KERNEL32.dll"* ]]
for symbol in ExitProcess VirtualAlloc VirtualProtect RaiseException \
              RtlAddFunctionTable RtlDeleteFunctionTable; do
    [[ "$imports" == *"Symbol: $symbol ("* ]] || {
        printf 'missing PE import: %s\n' "$symbol" >&2
        exit 1
    }
done
[[ "$(printf '%s\n' "$imports" | grep -c 'Symbol: ')" == 6 ]] || {
    printf 'unexpected extra PE import\n' >&2
    exit 1
}
[[ "$headers" == *"ExceptionTableRVA: 0x0"* ]]
[[ "$headers" == *"ExceptionTableSize: 0x0"* ]]
for expected in 'dyn_template T 0 0' 'dyn_code T 0 0' \
                'dyn_code_end T 37 0' 'dyn_unwind T 38 0' \
                'dyn_handler t 60 0' 'dyn_template_end T b0 0'; do
    [[ "$symbols" == *"$expected"* ]] || {
        printf 'unexpected copied-code layout: %s\n' "$expected" >&2
        exit 1
    }
done
binary_hex="$(od -An -v -tx1 bin/dynamic_unwind.exe | tr -d ' \n')"
[[ "$binary_hex" == *"090502000552013060000000"* ]] || {
    printf 'missing copied UNWIND_INFO and handler RVA bytes\n' >&2
    exit 1
}

{
    printf '# Generated by build.sh; contract-derived exit status, no native recording.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'machine = "IMAGE_FILE_MACHINE_AMD64"\n'
    printf 'exception_directory_size = 0\n'
    printf 'expected_exit = 0\n'
    printf 'imports = ["ExitProcess", "VirtualAlloc", "VirtualProtect", "RaiseException", "RtlAddFunctionTable", "RtlDeleteFunctionTable"]\n'
    printf 'template_rva_in_copied_blob = 0x0\n'
    printf 'function_begin_rva = 0x0\n'
    printf 'function_end_rva = 0x37\n'
    printf 'unwind_info_rva = 0x38\n'
    printf 'handler_rva = 0x60\n'
    printf 'copied_blob_bytes = 0xb0\n'
    printf 'unwind_info_hex = "090502000552013060000000"\n'
    for tool in clang linker dlltool readobj nm; do
        case "$tool" in
            clang) executable="$clang_bin";;
            linker) executable="$link_bin";;
            dlltool) executable="$dlltool_bin";;
            readobj) executable="$readobj_bin";;
            nm) executable="$nm_bin";;
        esac
        printf '%s_sha256 = "%s"\n' "$tool" \
            "$(shasum -a 256 "$(command -v "$executable")" | cut -d' ' -f1)"
    done
    for source in build.sh src/probe.c src/dynamic.S src/kernel32.def; do
        printf '\n[[source]]\npath = "%s"\nsha256 = "%s"\n' \
            "$source" "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    printf '\n[[fixture]]\npath = "bin/dynamic_unwind.exe"\n'
    printf 'sha256 = "%s"\n' \
        "$(shasum -a 256 bin/dynamic_unwind.exe | cut -d' ' -f1)"
    printf 'bytes = %s\n' "$(wc -c < bin/dynamic_unwind.exe | tr -d ' ')"
} > manifest.toml
