//! JIT runtime trampolines and guest-callout helper routines

// ---- split submodules ----
mod aarch64;
pub use aarch64::*;
mod ah_flags;
pub(crate) use ah_flags::*;
mod atomic;
pub use atomic::*;
mod bit_offset;
pub use bit_offset::*;
mod clobber;
pub use clobber::*;
mod clobber_evex_memory_sequences;
pub(crate) use clobber_evex_memory_sequences::*;
mod cmpccxadd;
mod cmpxchg;
mod evex_alignr_memory_source;
mod evex_bf16_memory_source;
mod evex_broadcast_interleave_memory_source;
mod evex_broadcast_logic_memory_source;
mod evex_broadcast_memory_features;
mod evex_broadcast_memory_source;
mod evex_bw_shuffle_madd_memory_source;
mod evex_chunk_insert_memory_source;
mod evex_chunk_shuffle_memory_source;
mod evex_compress_memory_destination;
mod evex_dbpsadbw_memory_source;
mod evex_duplicate_move_memory_features;
mod evex_duplicate_move_memory_source;
mod evex_expand_memory_source;
mod evex_extract_memory_destination;
mod evex_fixup_imm_memory_source;
mod evex_fma3_memory_source;
mod evex_four_dot_product_memory_source;
mod evex_four_fma_memory_source;
mod evex_fp16_arithmetic_memory_source;
mod evex_fp16_complex_memory_source;
mod evex_fp16_narrow_memory_destination;
mod evex_fp_arithmetic_memory_source;
mod evex_fp_class_memory_features;
mod evex_fp_class_memory_source;
mod evex_fp_compare_memory_source;
mod evex_fp_flag_compare_memory_source;
mod evex_fp_interleave_memory_source;
mod evex_fp_shuffle_memory_source;
mod evex_full_permute_memory_source;
mod evex_gfni_affine_memory_source;
mod evex_gfni_multiply_memory_source;
mod evex_half_move_memory_source;
mod evex_integer_arithmetic_memory_source;
mod evex_integer_interleave_memory_source;
mod evex_integer_mask_memory_source;
mod evex_integer_minmax_memory_source;
mod evex_integer_narrow_memory_destination;
mod evex_integer_pack_memory_source;
mod evex_integer_unary_memory_source;
mod evex_lane_shuffle_memory_source;
mod evex_logic_memory_source;
mod evex_mask_blend_memory_source;
mod evex_masked_logic_memory_source;
mod evex_memory_source_common;
mod evex_movntdqa_memory_features;
mod evex_movntdqa_memory_source;
mod evex_multishift_memory_source;
mod evex_packed_abs_memory_source;
mod evex_packed_convert_memory_source;
mod evex_packed_extend_memory_source;
mod evex_packed_fp16_convert_memory_source;
mod evex_packed_fp_unary_memory_source;
mod evex_packed_funnel_shift_memory_source;
mod evex_packed_move_memory_features;
mod evex_packed_move_memory_source;
mod evex_packed_rotate_memory_source;
mod evex_packed_shift_imm_memory_source;
mod evex_packed_variable_shift_memory_source;
mod evex_psadbw_memory_source;
mod evex_range_memory_source;
mod evex_scalar_fp_arithmetic_memory_source;
mod evex_scalar_fp_compare_memory_source;
mod evex_scalar_fp_convert_memory_source;
mod evex_scalar_fp_memory_features;
mod evex_scalar_fp_to_int_memory_source;
mod evex_scalar_fp_unary_memory_source;
mod evex_scalar_insert_memory_source;
mod evex_scalar_int_to_fp_memory_source;
mod evex_scalar_memory_source_common;
mod evex_scalar_move_memory_source;
mod evex_scale_f_memory_source;
mod evex_shared_count_shift_memory_source;
mod evex_ternary_logic_memory_source;
mod evex_two_table_permute_memory_source;
mod evex_variable_permute_memory_source;
mod evex_vector_align_memory_source;
mod evex_vp2intersect_memory_source;
mod evex_vpshufbitqmb_memory_source;
pub use cmpccxadd::*;
pub use cmpxchg::*;
mod crc32;
pub use crc32::*;
mod jit;
pub use jit::*;
mod scalar_alu;
pub(crate) use scalar_alu::*;
mod scalar_alu_memory;
pub(crate) use scalar_alu_memory::*;
mod scalar_alu_memory_folded;
pub(crate) use scalar_alu_memory_folded::*;
mod scalar_alu_virtuals;
pub(crate) use scalar_alu_virtuals::x86_jit_scalar_alu_function_virtuals_closed;
mod jit_bmi;
pub use jit_bmi::*;
mod jit_mul;
pub use jit_mul::*;
mod jit_shift;
pub use jit_shift::*;
mod maskmov;
pub use maskmov::*;
mod mem_state_compare;
pub use mem_state_compare::*;
mod misc;
pub use misc::*;
mod movbe;
pub use movbe::*;
mod movrs;
pub use movrs::*;
mod mxcsr;
pub use mxcsr::*;
mod push_value;
pub use push_value::*;
mod tbm;
pub use tbm::*;
mod vbit_select;
pub use vbit_select::*;
mod vector_compare;
pub use vector_compare::*;
mod xop;
pub use xop::*;
mod xchg;
pub(crate) use xchg::*;
mod mmx;
pub use mmx::*;
mod mmx_memory;
pub use mmx_memory::*;
mod vector;
mod vector_memory_source;
mod vector_replay_features;
mod vector_rotate;
mod vex_alignr_memory_source;
mod vex_broadcast_memory_source;
mod vex_cross_lane_128_memory_source;
mod vex_duplicate_move_memory_source;
mod vex_estimate_memory_source;
mod vex_extract_memory_destination;
mod vex_fma4_memory_source;
mod vex_fp16_narrow_memory_destination;
mod vex_fp_compare_memory_source;
mod vex_fp_dot_product_memory_source;
mod vex_fp_flag_compare_memory_source;
mod vex_fp_shuffle_memory_source;
mod vex_gfni_memory_source;
mod vex_half_move_memory_source;
mod vex_immediate_blend_memory_source;
mod vex_immediate_permute_memory_source;
mod vex_lane_shuffle_memory_source;
mod vex_masked_memory;
mod vex_movntdqa_memory_source;
mod vex_mpsadbw_memory_source;
mod vex_ne_convert_memory_source;
mod vex_packed_convert_memory_source;
mod vex_packed_extend_memory_source;
mod vex_packed_string_memory_source;
mod vex_ptest_memory_source;
mod vex_round_memory_source;
mod vex_scalar_convert_memory_source;
mod vex_scalar_fp_memory_source;
mod vex_scalar_insert_memory_source;
mod vex_scalar_integer_memory_source;
mod vex_sm3_sm4_memory_source;
mod vex_sqrt_memory_source;
mod vex_unary_memory_source;
mod vex_variable_blend_memory_source;
mod vex_variable_permute_memory_source;
mod vex_vpermil2_memory_source;
mod vpclmulqdq_memory_source;
use crate::smir::lower::runtime::*;
use crate::smir::lower::{
    X86_GUEST_APX_ENABLED_OFFSET, X86_GUEST_CALL_FN_OFFSET, X86_GUEST_CMPCCXADD_FN_OFFSET,
    X86_GUEST_CPL_OFFSET, X86_GUEST_CR0_OFFSET, X86_GUEST_CR4_OFFSET, X86_GUEST_CTX_OFFSET,
    X86_GUEST_EXIT_PC_OFFSET, X86_GUEST_FS_BASE_OFFSET, X86_GUEST_GPR_COUNT,
    X86_GUEST_GS_BASE_OFFSET, X86_GUEST_K_OFFSET, X86_GUEST_LOAD_FN_OFFSET, X86_GUEST_MM_OFFSET,
    X86_GUEST_MMX_ACTIVE_OFFSET, X86_GUEST_MXCSR_OFFSET, X86_GUEST_PAIR_LOAD_FN_OFFSET,
    X86_GUEST_PAIR_STORE_FN_OFFSET, X86_GUEST_RFLAGS_OFFSET, X86_GUEST_STORE_FN_OFFSET,
    X86_GUEST_TSC_AUX_OFFSET, X86_GUEST_VEC_LOAD_FN_OFFSET, X86_GUEST_VEC_STORE_FN_OFFSET,
    X86_GUEST_VECTOR_ACTIVE_OFFSET, X86_GUEST_X87_TAG_WORD_OFFSET, X86_GUEST_XCR0_OFFSET,
    X86_GUEST_XGETBV1_OFFSET, X86_GUEST_ZMM_OFFSET, X86_HOST_MXCSR_OFFSET, X86_STATE_PTR_AT_RBP,
};
pub(crate) use evex_alignr_memory_source::*;
pub(crate) use evex_bf16_memory_source::*;
pub(crate) use evex_broadcast_interleave_memory_source::*;
pub(crate) use evex_broadcast_logic_memory_source::*;
pub(crate) use evex_broadcast_memory_source::*;
pub(crate) use evex_bw_shuffle_madd_memory_source::*;
pub(crate) use evex_chunk_insert_memory_source::*;
pub(crate) use evex_chunk_shuffle_memory_source::*;
pub(crate) use evex_compress_memory_destination::*;
pub(crate) use evex_dbpsadbw_memory_source::*;
pub(crate) use evex_duplicate_move_memory_source::*;
pub(crate) use evex_expand_memory_source::*;
pub(crate) use evex_extract_memory_destination::*;
pub(crate) use evex_fixup_imm_memory_source::*;
pub(crate) use evex_fma3_memory_source::*;
pub(crate) use evex_four_dot_product_memory_source::*;
pub(crate) use evex_four_fma_memory_source::*;
pub(crate) use evex_fp_arithmetic_memory_source::*;
pub(crate) use evex_fp_class_memory_features::*;
pub(crate) use evex_fp_class_memory_source::*;
pub(crate) use evex_fp_compare_memory_source::*;
pub(crate) use evex_fp_flag_compare_memory_source::*;
pub(crate) use evex_fp_interleave_memory_source::*;
pub(crate) use evex_fp_shuffle_memory_source::*;
pub(crate) use evex_fp16_arithmetic_memory_source::*;
pub(crate) use evex_fp16_complex_memory_source::*;
pub(crate) use evex_fp16_narrow_memory_destination::*;
pub(crate) use evex_full_permute_memory_source::*;
pub(crate) use evex_gfni_affine_memory_source::*;
pub(crate) use evex_gfni_multiply_memory_source::*;
pub(crate) use evex_half_move_memory_source::*;
pub(crate) use evex_integer_arithmetic_memory_source::*;
pub(crate) use evex_integer_interleave_memory_source::*;
pub(crate) use evex_integer_mask_memory_source::*;
pub(crate) use evex_integer_minmax_memory_source::*;
pub(crate) use evex_integer_narrow_memory_destination::*;
pub(crate) use evex_integer_pack_memory_source::*;
pub(crate) use evex_integer_unary_memory_source::*;
pub(crate) use evex_lane_shuffle_memory_source::*;
pub(crate) use evex_logic_memory_source::*;
pub(crate) use evex_mask_blend_memory_source::*;
pub(crate) use evex_masked_logic_memory_source::*;
pub(crate) use evex_movntdqa_memory_source::*;
pub(crate) use evex_multishift_memory_source::*;
pub(crate) use evex_packed_abs_memory_source::*;
pub(crate) use evex_packed_convert_memory_source::*;
pub(crate) use evex_packed_extend_memory_source::*;
pub(crate) use evex_packed_fp_unary_memory_source::*;
pub(crate) use evex_packed_fp16_convert_memory_source::*;
pub(crate) use evex_packed_funnel_shift_memory_source::*;
pub(crate) use evex_packed_move_memory_source::*;
pub(crate) use evex_packed_rotate_memory_source::*;
pub(crate) use evex_packed_shift_imm_memory_source::*;
pub(crate) use evex_packed_variable_shift_memory_source::*;
pub(crate) use evex_psadbw_memory_source::*;
pub(crate) use evex_range_memory_source::*;
pub(crate) use evex_scalar_fp_arithmetic_memory_source::*;
pub(crate) use evex_scalar_fp_compare_memory_source::*;
pub(crate) use evex_scalar_fp_convert_memory_source::*;
pub(crate) use evex_scalar_fp_to_int_memory_source::*;
pub(crate) use evex_scalar_fp_unary_memory_source::*;
pub(crate) use evex_scalar_insert_memory_source::*;
pub(crate) use evex_scalar_int_to_fp_memory_source::*;
pub(crate) use evex_scalar_move_memory_source::*;
pub(crate) use evex_scale_f_memory_source::*;
pub(crate) use evex_shared_count_shift_memory_source::*;
pub(crate) use evex_ternary_logic_memory_source::*;
pub(crate) use evex_two_table_permute_memory_source::*;
pub(crate) use evex_variable_permute_memory_source::*;
pub(crate) use evex_vector_align_memory_source::*;
pub(crate) use evex_vp2intersect_memory_source::*;
pub(crate) use evex_vpshufbitqmb_memory_source::*;
pub use vector::*;
mod vector_k16;
pub use vector_k16::*;
pub(crate) use vector_memory_source::*;
pub(crate) use vector_replay_features::*;
pub(crate) use vector_rotate::*;
pub(crate) use vex_alignr_memory_source::*;
pub(crate) use vex_broadcast_memory_source::*;
pub(crate) use vex_cross_lane_128_memory_source::*;
pub(crate) use vex_duplicate_move_memory_source::*;
pub(crate) use vex_estimate_memory_source::*;
pub(crate) use vex_extract_memory_destination::*;
pub(crate) use vex_fma4_memory_source::*;
pub(crate) use vex_fp_compare_memory_source::*;
pub(crate) use vex_fp_dot_product_memory_source::*;
pub(crate) use vex_fp_flag_compare_memory_source::*;
pub(crate) use vex_fp_shuffle_memory_source::*;
pub(crate) use vex_fp16_narrow_memory_destination::*;
pub(crate) use vex_gfni_memory_source::*;
pub(crate) use vex_half_move_memory_source::*;
pub(crate) use vex_immediate_blend_memory_source::*;
pub(crate) use vex_immediate_permute_memory_source::*;
pub(crate) use vex_lane_shuffle_memory_source::*;
pub(crate) use vex_masked_memory::*;
pub(crate) use vex_movntdqa_memory_source::*;
pub(crate) use vex_mpsadbw_memory_source::*;
pub(crate) use vex_ne_convert_memory_source::*;
pub(crate) use vex_packed_convert_memory_source::*;
pub(crate) use vex_packed_extend_memory_source::*;
pub(crate) use vex_packed_string_memory_source::*;
pub(crate) use vex_ptest_memory_source::*;
pub(crate) use vex_round_memory_source::*;
pub(crate) use vex_scalar_convert_memory_source::*;
pub(crate) use vex_scalar_fp_memory_source::*;
pub(crate) use vex_scalar_insert_memory_source::*;
pub(crate) use vex_scalar_integer_memory_source::*;
pub(crate) use vex_sm3_sm4_memory_source::*;
pub(crate) use vex_sqrt_memory_source::*;
pub(crate) use vex_unary_memory_source::*;
pub(crate) use vex_variable_blend_memory_source::*;
pub(crate) use vex_variable_permute_memory_source::*;
pub(crate) use vex_vpermil2_memory_source::*;
pub(crate) use vpclmulqdq_memory_source::*;
