#!/usr/bin/env python3
"""Generate the Darwin personality's MIG message-ID table from vendored XNU
MIG definitions.

Inputs (under docs/specifications/darwin/xnu-12377.121.6/osfmk): the
subsystem definitions listed in SUBSYSTEMS and the .defs/.h files they
include (std_types.defs, mach_types.defs, clock_types.defs,
machine/machine_types.defs, machine/thread_state.h, mach_debug/
mach_debug_types.defs).

Each file is compiled with the host's `mig` (bootstrap_cmds; macOS only) as
a user of the interface would compile it (no KERNEL_SERVER), and the
generated server's routine table gives every routine's message ID: the
subsystem base plus its index, `skip` entries included.

Output: src/user/darwin/mig/ids.rs (overwritten). With --check, nothing is
written and the script fails if the file differs from what it would write.
"""

import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
XNU = os.path.join(ROOT, "docs/specifications/darwin/xnu-12377.121.6")
OUT = os.path.join(ROOT, "src/user/darwin/mig/ids.rs")

# (defs file under osfmk/mach, Rust module name)
SUBSYSTEMS = [
    ("clock.defs", "clock"),
    ("mach_host.defs", "host"),
    ("host_priv.defs", "host_priv"),
    ("mach_port.defs", "mach_port"),
    ("mach_vm.defs", "mach_vm"),
    ("mach_voucher.defs", "mach_voucher"),
    ("memory_entry.defs", "memory_entry"),
    ("processor_set.defs", "processor_set"),
    ("restartable.defs", "task_restartable"),
    ("semaphore.defs", "semaphore"),
    ("task.defs", "task"),
    ("thread_act.defs", "thread_act"),
    ("vm_map.defs", "vm_map"),
]


def sdk():
    return subprocess.check_output(["xcrun", "--show-sdk-path"], text=True).strip()


def routines(defs, sysroot, tmp):
    server = os.path.join(tmp, "server.c")
    subprocess.check_call(
        [
            "mig",
            "-isysroot", sysroot,
            "-I" + os.path.join(XNU, "osfmk"),
            "-server", server,
            "-user", os.devnull,
            "-header", os.devnull,
            "-sheader", os.devnull,
            os.path.join(XNU, "osfmk/mach", defs),
        ],
        cwd=tmp,
    )
    text = open(server).read()
    m = re.search(
        r"const struct (\w+) \1 = \{\s*\w+,\s*(\d+),\s*(\d+),.*?\{\s*(.*?)\n\t\}\s*\};",
        text,
        re.S,
    )
    if not m:
        raise SystemExit(f"{defs}: no subsystem table")
    base, end = int(m.group(2)), int(m.group(3))
    entries = re.findall(r"\{\s*(\(mig_impl_routine_t\) 0,\s*\(mig_stub_routine_t\) _X(\w+)|0, 0, 0, 0, 0, 0)", m.group(4))
    names = [e[1] if e[1] else None for e in entries]
    if base + len(names) != end:
        raise SystemExit(f"{defs}: {len(names)} entries for ids {base}..{end}")
    return base, names


def main():
    sysroot = sdk()
    out = [
        "// @generated by tools/darwin/gen_mig.py from XNU 12377.121.6",
        "// (docs/specifications/darwin/xnu-12377.121.6). Do not edit by hand.",
        "",
        "//! MIG message IDs of the kernel's subsystems (`msgh_id` of each",
        "//! routine's request; its reply's is 100 more).",
        "",
    ]
    table = []
    for defs, module in SUBSYSTEMS:
        with tempfile.TemporaryDirectory() as tmp:
            base, names = routines(defs, sysroot, tmp)
        out.append(f"/// `{defs}` (subsystem {base}).")
        out.append(f"pub mod {module} {{")
        out.append(f"    /// The subsystem's first message ID.")
        out.append(f"    pub const BASE: i32 = {base};")
        for i, n in enumerate(names):
            if n is None:
                continue
            const = n.lstrip("_").upper()
            out.append(f"    /// `{n}`.")
            out.append(f"    pub const {const}: i32 = {base + i};")
            table.append((base + i, n))
        out.append("}")
        out.append("")
    table.sort()
    out.append("/// Every routine by message ID, sorted (for tracing).")
    out.append(f"pub static NAMES: [(i32, &str); {len(table)}] = [")
    for i, n in table:
        out.append(f'    ({i}, "{n}"),')
    out.append("];")
    out.append("")
    out.append("/// The routine name of request `id`.")
    out.append("pub fn name(id: i32) -> Option<&'static str> {")
    out.append("    NAMES.binary_search_by_key(&id, |e| e.0).ok().map(|i| NAMES[i].1)")
    out.append("}")
    out.append("")
    # Formatted as rustfmt (edition 2024) formats the checked-in file.
    text = subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input="\n".join(out), capture_output=True, text=True, check=True,
    ).stdout
    if "--check" in sys.argv[1:]:
        with open(OUT) as f:
            if f.read() != text:
                raise SystemExit(f"{OUT} is stale: run tools/darwin/gen_mig.py")
        print(f"{OUT}: {len(table)} routines (checked)", file=sys.stderr)
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT}: {len(table)} routines", file=sys.stderr)


if __name__ == "__main__":
    main()
