#!/usr/bin/env python3
"""Generate the Darwin personality's table of the arm64 kernel's `hw` and
`machdep` sysctl nodes from a recorded host probe.

Input: docs/specifications/darwin/macos-27.2-26B5091g/
sysctl-hw-machdep-arm64.tsv, written by tools/darwin/sysctl_dump.c: one
node per line, tab-separated name, OID (comma-separated), kind (hex),
format, and description, with `\\t`, `\\n`, and `\\\\` escapes.

Output: src/user/darwin/syscall/bsd/sysctl/arm64.rs (overwritten): the
nodes sorted by OID. With --check, nothing is written and the script fails
if the file differs from what it would write.
"""

import os
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PROBE = "docs/specifications/darwin/macos-27.2-26B5091g/sysctl-hw-machdep-arm64.tsv"
OUT = os.path.join(ROOT, "src/user/darwin/syscall/bsd/sysctl/arm64.rs")


def unescape(field):
    out, i = [], 0
    while i < len(field):
        c = field[i]
        if c == "\\" and i + 1 < len(field):
            out.append({"t": "\t", "n": "\n", "\\": "\\"}[field[i + 1]])
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t") + '"'


def main():
    rows = []
    with open(os.path.join(ROOT, PROBE)) as f:
        for line in f:
            name, oid, kind, fmt, descr = line.rstrip("\n").split("\t")
            oid = [int(x) for x in oid.split(",")]
            rows.append((oid, unescape(name), int(kind, 16), unescape(fmt), unescape(descr)))
    rows.sort(key=lambda r: r[0])
    out = [
        "// @generated by tools/darwin/gen_sysctl.py from",
        f"// {PROBE}. Do not edit by hand.",
        "",
        "//! The arm64 kernel's `hw` and `machdep` sysctl nodes (macOS 27.2,",
        "//! 26B5091g): OID, name, kind, format, and description, sorted by OID.",
        "",
        "use super::tree::Row;",
        "",
        "/// The nodes.",
        "#[rustfmt::skip]",
        "pub static ROWS: &[Row] = &[",
    ]
    for oid, name, kind, fmt, descr in rows:
        out.append(
            f"    Row {{ oid: &{oid}, name: {rust_str(name)}, kind: {kind:#010x}, "
            f"fmt: {rust_str(fmt)}, descr: {rust_str(descr)} }},"
        )
    out.append("];")
    out.append("")
    text = "\n".join(out)
    # The file is left as rustfmt (edition 2024) leaves it.
    text = subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=text, capture_output=True, text=True, check=True,
    ).stdout
    if "--check" in sys.argv[1:]:
        with open(OUT) as f:
            if f.read() != text:
                raise SystemExit(f"{OUT} is stale: run tools/darwin/gen_sysctl.py")
        print(f"{OUT}: {len(rows)} nodes (checked)", file=sys.stderr)
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT}: {len(rows)} nodes", file=sys.stderr)


if __name__ == "__main__":
    main()
