#!/usr/bin/env bash
# Rebuild the three freestanding PE fixtures. No SDK or CRT is required.
set -euo pipefail

fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-fixtures.XXXXXX")"
trap 'rm -f "$task_dir/smoke.obj" "$task_dir/kernel32.lib"; rmdir "$task_dir"' EXIT

clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=.)

cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; def=src/kernel32-x86.def; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; def=src/kernel32.def; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; def=src/kernel32.def; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    mkdir -p "bin/$arch"
    "$dlltool_bin" -m "$dllmachine" -k -d "$def" -l "$task_dir/kernel32.lib"
    "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" -c src/smoke.c -o "$task_dir/smoke.obj"
    "$link_bin" /machine:"$machine" /entry:entry /subsystem:console /nodefaultlib \
        /timestamp:0 /dynamicbase /nxcompat /stack:1048576,4096 /heap:1048576,4096 \
        /out:"bin/$arch/smoke.exe" "$task_dir/smoke.obj" "$task_dir/kernel32.lib"
done

{
    printf '# Generated by build.sh. Expected exit status follows documented API contracts; no native recording exists.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'source = "src/smoke.c"\n'
    printf 'source_sha256 = "%s"\n' "$(shasum -a 256 src/smoke.c | cut -d' ' -f1)"
    printf 'oracle = "Microsoft API and ABI specifications; native Windows execution unknown"\n'
    printf 'expected_exit = 0\n'
    for arch in x86 x64 arm64; do
        printf '\n[[fixture]]\npath = "bin/%s/smoke.exe"\n' "$arch"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/smoke.exe" | cut -d' ' -f1)"
        printf 'bytes = %s\n' "$(wc -c < "bin/$arch/smoke.exe" | tr -d ' ')"
    done
} > manifest.toml
