#!/usr/bin/env bash
# Services fixture rebuild; existing smoke binaries remain untouched.
set -euo pipefail
fixture_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
task_dir="$(mktemp -d "${TMPDIR:-/tmp}/rax-windows-services.XXXXXX")"
trap 'rm -f "$task_dir/services.obj" "$task_dir/kernel32.lib"; rmdir "$task_dir"' EXIT
clang_bin="${CLANG_BIN:-clang}"
link_bin="${LLD_LINK_BIN:-lld-link}"
dlltool_bin="${LLVM_DLLTOOL_BIN:-llvm-dlltool}"
flags=(-Oz -ffreestanding -fno-builtin -fno-stack-protector -fno-ident
       -fno-vectorize -fno-slp-vectorize -fno-asynchronous-unwind-tables
       -fno-unwind-tables -ffile-prefix-map="$fixture_dir"=.)
cd "$fixture_dir"
for arch in x86 x64 arm64; do
    case "$arch" in
        x86) target=i686-pc-windows-msvc; machine=x86; dllmachine=i386; def=src/services-kernel32-x86.def; extra=();;
        x64) target=x86_64-pc-windows-msvc; machine=x64; dllmachine=i386:x86-64; def=src/services-kernel32.def; extra=();;
        arm64) target=aarch64-pc-windows-msvc; machine=arm64; dllmachine=arm64; def=src/services-kernel32.def; extra=(-mgeneral-regs-only -ffixed-x18);;
    esac
    mkdir -p "bin/$arch"
    "$dlltool_bin" -m "$dllmachine" -k -d "$def" -l "$task_dir/kernel32.lib"
    "$clang_bin" --target="$target" "${flags[@]}" "${extra[@]}" -c src/services.c -o "$task_dir/services.obj"
    "$link_bin" /machine:"$machine" /entry:entry /subsystem:console /nodefaultlib \
        /timestamp:0 /dynamicbase /nxcompat /stack:1048576,4096 /heap:1048576,4096 \
        /out:"bin/$arch/services.exe" "$task_dir/services.obj" "$task_dir/kernel32.lib"
done
{
    printf '# Generated by build-services.sh. Native Windows recording unknown.\n'
    printf 'clang = "%s"\n' "$("$clang_bin" --version | head -1)"
    printf 'linker = "%s"\n' "$("$link_bin" --version)"
    printf 'oracle = "Microsoft API/ABI contracts; not a native differential oracle"\n'
    printf 'expected_exit = 0\n'
    for source in src/services.c src/services-kernel32.def src/services-kernel32-x86.def build-services.sh; do
        printf '\n[[source]]\npath = "%s"\n' "$source"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "$source" | cut -d' ' -f1)"
    done
    for arch in x86 x64 arm64; do
        printf '\n[[fixture]]\npath = "bin/%s/services.exe"\n' "$arch"
        printf 'sha256 = "%s"\n' "$(shasum -a 256 "bin/$arch/services.exe" | cut -d' ' -f1)"
        printf 'bytes = %s\n' "$(wc -c < "bin/$arch/services.exe" | tr -d ' ')"
    done
} > services-manifest.toml
