// @generated by tools/linux/gen_syscalls.py from the Linux 6.19 UAPI
// headers in docs/specifications/linux/uapi-6.19. Do not edit by hand.

//! Linux `errno` values (`asm-generic/errno-base.h`, `asm-generic/errno.h`),
//! shared by every supported ABI.

/// `EPERM`
pub const EPERM: i32 = 1;
/// `ENOENT`
pub const ENOENT: i32 = 2;
/// `ESRCH`
pub const ESRCH: i32 = 3;
/// `EINTR`
pub const EINTR: i32 = 4;
/// `EIO`
pub const EIO: i32 = 5;
/// `ENXIO`
pub const ENXIO: i32 = 6;
/// `E2BIG`
pub const E2BIG: i32 = 7;
/// `ENOEXEC`
pub const ENOEXEC: i32 = 8;
/// `EBADF`
pub const EBADF: i32 = 9;
/// `ECHILD`
pub const ECHILD: i32 = 10;
/// `EAGAIN`
pub const EAGAIN: i32 = 11;
/// `ENOMEM`
pub const ENOMEM: i32 = 12;
/// `EACCES`
pub const EACCES: i32 = 13;
/// `EFAULT`
pub const EFAULT: i32 = 14;
/// `ENOTBLK`
pub const ENOTBLK: i32 = 15;
/// `EBUSY`
pub const EBUSY: i32 = 16;
/// `EEXIST`
pub const EEXIST: i32 = 17;
/// `EXDEV`
pub const EXDEV: i32 = 18;
/// `ENODEV`
pub const ENODEV: i32 = 19;
/// `ENOTDIR`
pub const ENOTDIR: i32 = 20;
/// `EISDIR`
pub const EISDIR: i32 = 21;
/// `EINVAL`
pub const EINVAL: i32 = 22;
/// `ENFILE`
pub const ENFILE: i32 = 23;
/// `EMFILE`
pub const EMFILE: i32 = 24;
/// `ENOTTY`
pub const ENOTTY: i32 = 25;
/// `ETXTBSY`
pub const ETXTBSY: i32 = 26;
/// `EFBIG`
pub const EFBIG: i32 = 27;
/// `ENOSPC`
pub const ENOSPC: i32 = 28;
/// `ESPIPE`
pub const ESPIPE: i32 = 29;
/// `EROFS`
pub const EROFS: i32 = 30;
/// `EMLINK`
pub const EMLINK: i32 = 31;
/// `EPIPE`
pub const EPIPE: i32 = 32;
/// `EDOM`
pub const EDOM: i32 = 33;
/// `ERANGE`
pub const ERANGE: i32 = 34;
/// `EDEADLK`
pub const EDEADLK: i32 = 35;
/// `ENAMETOOLONG`
pub const ENAMETOOLONG: i32 = 36;
/// `ENOLCK`
pub const ENOLCK: i32 = 37;
/// `ENOSYS`
pub const ENOSYS: i32 = 38;
/// `ENOTEMPTY`
pub const ENOTEMPTY: i32 = 39;
/// `ELOOP`
pub const ELOOP: i32 = 40;
/// `ENOMSG`
pub const ENOMSG: i32 = 42;
/// `EIDRM`
pub const EIDRM: i32 = 43;
/// `ECHRNG`
pub const ECHRNG: i32 = 44;
/// `EL2NSYNC`
pub const EL2NSYNC: i32 = 45;
/// `EL3HLT`
pub const EL3HLT: i32 = 46;
/// `EL3RST`
pub const EL3RST: i32 = 47;
/// `ELNRNG`
pub const ELNRNG: i32 = 48;
/// `EUNATCH`
pub const EUNATCH: i32 = 49;
/// `ENOCSI`
pub const ENOCSI: i32 = 50;
/// `EL2HLT`
pub const EL2HLT: i32 = 51;
/// `EBADE`
pub const EBADE: i32 = 52;
/// `EBADR`
pub const EBADR: i32 = 53;
/// `EXFULL`
pub const EXFULL: i32 = 54;
/// `ENOANO`
pub const ENOANO: i32 = 55;
/// `EBADRQC`
pub const EBADRQC: i32 = 56;
/// `EBADSLT`
pub const EBADSLT: i32 = 57;
/// `EBFONT`
pub const EBFONT: i32 = 59;
/// `ENOSTR`
pub const ENOSTR: i32 = 60;
/// `ENODATA`
pub const ENODATA: i32 = 61;
/// `ETIME`
pub const ETIME: i32 = 62;
/// `ENOSR`
pub const ENOSR: i32 = 63;
/// `ENONET`
pub const ENONET: i32 = 64;
/// `ENOPKG`
pub const ENOPKG: i32 = 65;
/// `EREMOTE`
pub const EREMOTE: i32 = 66;
/// `ENOLINK`
pub const ENOLINK: i32 = 67;
/// `EADV`
pub const EADV: i32 = 68;
/// `ESRMNT`
pub const ESRMNT: i32 = 69;
/// `ECOMM`
pub const ECOMM: i32 = 70;
/// `EPROTO`
pub const EPROTO: i32 = 71;
/// `EMULTIHOP`
pub const EMULTIHOP: i32 = 72;
/// `EDOTDOT`
pub const EDOTDOT: i32 = 73;
/// `EBADMSG`
pub const EBADMSG: i32 = 74;
/// `EOVERFLOW`
pub const EOVERFLOW: i32 = 75;
/// `ENOTUNIQ`
pub const ENOTUNIQ: i32 = 76;
/// `EBADFD`
pub const EBADFD: i32 = 77;
/// `EREMCHG`
pub const EREMCHG: i32 = 78;
/// `ELIBACC`
pub const ELIBACC: i32 = 79;
/// `ELIBBAD`
pub const ELIBBAD: i32 = 80;
/// `ELIBSCN`
pub const ELIBSCN: i32 = 81;
/// `ELIBMAX`
pub const ELIBMAX: i32 = 82;
/// `ELIBEXEC`
pub const ELIBEXEC: i32 = 83;
/// `EILSEQ`
pub const EILSEQ: i32 = 84;
/// `ERESTART`
pub const ERESTART: i32 = 85;
/// `ESTRPIPE`
pub const ESTRPIPE: i32 = 86;
/// `EUSERS`
pub const EUSERS: i32 = 87;
/// `ENOTSOCK`
pub const ENOTSOCK: i32 = 88;
/// `EDESTADDRREQ`
pub const EDESTADDRREQ: i32 = 89;
/// `EMSGSIZE`
pub const EMSGSIZE: i32 = 90;
/// `EPROTOTYPE`
pub const EPROTOTYPE: i32 = 91;
/// `ENOPROTOOPT`
pub const ENOPROTOOPT: i32 = 92;
/// `EPROTONOSUPPORT`
pub const EPROTONOSUPPORT: i32 = 93;
/// `ESOCKTNOSUPPORT`
pub const ESOCKTNOSUPPORT: i32 = 94;
/// `EOPNOTSUPP`
pub const EOPNOTSUPP: i32 = 95;
/// `EPFNOSUPPORT`
pub const EPFNOSUPPORT: i32 = 96;
/// `EAFNOSUPPORT`
pub const EAFNOSUPPORT: i32 = 97;
/// `EADDRINUSE`
pub const EADDRINUSE: i32 = 98;
/// `EADDRNOTAVAIL`
pub const EADDRNOTAVAIL: i32 = 99;
/// `ENETDOWN`
pub const ENETDOWN: i32 = 100;
/// `ENETUNREACH`
pub const ENETUNREACH: i32 = 101;
/// `ENETRESET`
pub const ENETRESET: i32 = 102;
/// `ECONNABORTED`
pub const ECONNABORTED: i32 = 103;
/// `ECONNRESET`
pub const ECONNRESET: i32 = 104;
/// `ENOBUFS`
pub const ENOBUFS: i32 = 105;
/// `EISCONN`
pub const EISCONN: i32 = 106;
/// `ENOTCONN`
pub const ENOTCONN: i32 = 107;
/// `ESHUTDOWN`
pub const ESHUTDOWN: i32 = 108;
/// `ETOOMANYREFS`
pub const ETOOMANYREFS: i32 = 109;
/// `ETIMEDOUT`
pub const ETIMEDOUT: i32 = 110;
/// `ECONNREFUSED`
pub const ECONNREFUSED: i32 = 111;
/// `EHOSTDOWN`
pub const EHOSTDOWN: i32 = 112;
/// `EHOSTUNREACH`
pub const EHOSTUNREACH: i32 = 113;
/// `EALREADY`
pub const EALREADY: i32 = 114;
/// `EINPROGRESS`
pub const EINPROGRESS: i32 = 115;
/// `ESTALE`
pub const ESTALE: i32 = 116;
/// `EUCLEAN`
pub const EUCLEAN: i32 = 117;
/// `ENOTNAM`
pub const ENOTNAM: i32 = 118;
/// `ENAVAIL`
pub const ENAVAIL: i32 = 119;
/// `EISNAM`
pub const EISNAM: i32 = 120;
/// `EREMOTEIO`
pub const EREMOTEIO: i32 = 121;
/// `EDQUOT`
pub const EDQUOT: i32 = 122;
/// `ENOMEDIUM`
pub const ENOMEDIUM: i32 = 123;
/// `EMEDIUMTYPE`
pub const EMEDIUMTYPE: i32 = 124;
/// `ECANCELED`
pub const ECANCELED: i32 = 125;
/// `ENOKEY`
pub const ENOKEY: i32 = 126;
/// `EKEYEXPIRED`
pub const EKEYEXPIRED: i32 = 127;
/// `EKEYREVOKED`
pub const EKEYREVOKED: i32 = 128;
/// `EKEYREJECTED`
pub const EKEYREJECTED: i32 = 129;
/// `EOWNERDEAD`
pub const EOWNERDEAD: i32 = 130;
/// `ENOTRECOVERABLE`
pub const ENOTRECOVERABLE: i32 = 131;
/// `ERFKILL`
pub const ERFKILL: i32 = 132;
/// `EHWPOISON`
pub const EHWPOISON: i32 = 133;
/// `EWOULDBLOCK` (alias of `EAGAIN`)
pub const EWOULDBLOCK: i32 = EAGAIN;
/// `EDEADLOCK` (alias of `EDEADLK`)
pub const EDEADLOCK: i32 = EDEADLK;

/// The canonical name of a Linux errno value.
pub const fn errno_name(errno: i32) -> Option<&'static str> {
    Some(match errno {
        1 => "EPERM",
        2 => "ENOENT",
        3 => "ESRCH",
        4 => "EINTR",
        5 => "EIO",
        6 => "ENXIO",
        7 => "E2BIG",
        8 => "ENOEXEC",
        9 => "EBADF",
        10 => "ECHILD",
        11 => "EAGAIN",
        12 => "ENOMEM",
        13 => "EACCES",
        14 => "EFAULT",
        15 => "ENOTBLK",
        16 => "EBUSY",
        17 => "EEXIST",
        18 => "EXDEV",
        19 => "ENODEV",
        20 => "ENOTDIR",
        21 => "EISDIR",
        22 => "EINVAL",
        23 => "ENFILE",
        24 => "EMFILE",
        25 => "ENOTTY",
        26 => "ETXTBSY",
        27 => "EFBIG",
        28 => "ENOSPC",
        29 => "ESPIPE",
        30 => "EROFS",
        31 => "EMLINK",
        32 => "EPIPE",
        33 => "EDOM",
        34 => "ERANGE",
        35 => "EDEADLK",
        36 => "ENAMETOOLONG",
        37 => "ENOLCK",
        38 => "ENOSYS",
        39 => "ENOTEMPTY",
        40 => "ELOOP",
        42 => "ENOMSG",
        43 => "EIDRM",
        44 => "ECHRNG",
        45 => "EL2NSYNC",
        46 => "EL3HLT",
        47 => "EL3RST",
        48 => "ELNRNG",
        49 => "EUNATCH",
        50 => "ENOCSI",
        51 => "EL2HLT",
        52 => "EBADE",
        53 => "EBADR",
        54 => "EXFULL",
        55 => "ENOANO",
        56 => "EBADRQC",
        57 => "EBADSLT",
        59 => "EBFONT",
        60 => "ENOSTR",
        61 => "ENODATA",
        62 => "ETIME",
        63 => "ENOSR",
        64 => "ENONET",
        65 => "ENOPKG",
        66 => "EREMOTE",
        67 => "ENOLINK",
        68 => "EADV",
        69 => "ESRMNT",
        70 => "ECOMM",
        71 => "EPROTO",
        72 => "EMULTIHOP",
        73 => "EDOTDOT",
        74 => "EBADMSG",
        75 => "EOVERFLOW",
        76 => "ENOTUNIQ",
        77 => "EBADFD",
        78 => "EREMCHG",
        79 => "ELIBACC",
        80 => "ELIBBAD",
        81 => "ELIBSCN",
        82 => "ELIBMAX",
        83 => "ELIBEXEC",
        84 => "EILSEQ",
        85 => "ERESTART",
        86 => "ESTRPIPE",
        87 => "EUSERS",
        88 => "ENOTSOCK",
        89 => "EDESTADDRREQ",
        90 => "EMSGSIZE",
        91 => "EPROTOTYPE",
        92 => "ENOPROTOOPT",
        93 => "EPROTONOSUPPORT",
        94 => "ESOCKTNOSUPPORT",
        95 => "EOPNOTSUPP",
        96 => "EPFNOSUPPORT",
        97 => "EAFNOSUPPORT",
        98 => "EADDRINUSE",
        99 => "EADDRNOTAVAIL",
        100 => "ENETDOWN",
        101 => "ENETUNREACH",
        102 => "ENETRESET",
        103 => "ECONNABORTED",
        104 => "ECONNRESET",
        105 => "ENOBUFS",
        106 => "EISCONN",
        107 => "ENOTCONN",
        108 => "ESHUTDOWN",
        109 => "ETOOMANYREFS",
        110 => "ETIMEDOUT",
        111 => "ECONNREFUSED",
        112 => "EHOSTDOWN",
        113 => "EHOSTUNREACH",
        114 => "EALREADY",
        115 => "EINPROGRESS",
        116 => "ESTALE",
        117 => "EUCLEAN",
        118 => "ENOTNAM",
        119 => "ENAVAIL",
        120 => "EISNAM",
        121 => "EREMOTEIO",
        122 => "EDQUOT",
        123 => "ENOMEDIUM",
        124 => "EMEDIUMTYPE",
        125 => "ECANCELED",
        126 => "ENOKEY",
        127 => "EKEYEXPIRED",
        128 => "EKEYREVOKED",
        129 => "EKEYREJECTED",
        130 => "EOWNERDEAD",
        131 => "ENOTRECOVERABLE",
        132 => "ERFKILL",
        133 => "EHWPOISON",
        _ => return None,
    })
}

/// Every `(name, value)` pair, including aliases, in header order.
pub const ERRNO_TABLE: &[(&str, i32)] = &[
    ("EPERM", 1),
    ("ENOENT", 2),
    ("ESRCH", 3),
    ("EINTR", 4),
    ("EIO", 5),
    ("ENXIO", 6),
    ("E2BIG", 7),
    ("ENOEXEC", 8),
    ("EBADF", 9),
    ("ECHILD", 10),
    ("EAGAIN", 11),
    ("ENOMEM", 12),
    ("EACCES", 13),
    ("EFAULT", 14),
    ("ENOTBLK", 15),
    ("EBUSY", 16),
    ("EEXIST", 17),
    ("EXDEV", 18),
    ("ENODEV", 19),
    ("ENOTDIR", 20),
    ("EISDIR", 21),
    ("EINVAL", 22),
    ("ENFILE", 23),
    ("EMFILE", 24),
    ("ENOTTY", 25),
    ("ETXTBSY", 26),
    ("EFBIG", 27),
    ("ENOSPC", 28),
    ("ESPIPE", 29),
    ("EROFS", 30),
    ("EMLINK", 31),
    ("EPIPE", 32),
    ("EDOM", 33),
    ("ERANGE", 34),
    ("EDEADLK", 35),
    ("ENAMETOOLONG", 36),
    ("ENOLCK", 37),
    ("ENOSYS", 38),
    ("ENOTEMPTY", 39),
    ("ELOOP", 40),
    ("ENOMSG", 42),
    ("EIDRM", 43),
    ("ECHRNG", 44),
    ("EL2NSYNC", 45),
    ("EL3HLT", 46),
    ("EL3RST", 47),
    ("ELNRNG", 48),
    ("EUNATCH", 49),
    ("ENOCSI", 50),
    ("EL2HLT", 51),
    ("EBADE", 52),
    ("EBADR", 53),
    ("EXFULL", 54),
    ("ENOANO", 55),
    ("EBADRQC", 56),
    ("EBADSLT", 57),
    ("EBFONT", 59),
    ("ENOSTR", 60),
    ("ENODATA", 61),
    ("ETIME", 62),
    ("ENOSR", 63),
    ("ENONET", 64),
    ("ENOPKG", 65),
    ("EREMOTE", 66),
    ("ENOLINK", 67),
    ("EADV", 68),
    ("ESRMNT", 69),
    ("ECOMM", 70),
    ("EPROTO", 71),
    ("EMULTIHOP", 72),
    ("EDOTDOT", 73),
    ("EBADMSG", 74),
    ("EOVERFLOW", 75),
    ("ENOTUNIQ", 76),
    ("EBADFD", 77),
    ("EREMCHG", 78),
    ("ELIBACC", 79),
    ("ELIBBAD", 80),
    ("ELIBSCN", 81),
    ("ELIBMAX", 82),
    ("ELIBEXEC", 83),
    ("EILSEQ", 84),
    ("ERESTART", 85),
    ("ESTRPIPE", 86),
    ("EUSERS", 87),
    ("ENOTSOCK", 88),
    ("EDESTADDRREQ", 89),
    ("EMSGSIZE", 90),
    ("EPROTOTYPE", 91),
    ("ENOPROTOOPT", 92),
    ("EPROTONOSUPPORT", 93),
    ("ESOCKTNOSUPPORT", 94),
    ("EOPNOTSUPP", 95),
    ("EPFNOSUPPORT", 96),
    ("EAFNOSUPPORT", 97),
    ("EADDRINUSE", 98),
    ("EADDRNOTAVAIL", 99),
    ("ENETDOWN", 100),
    ("ENETUNREACH", 101),
    ("ENETRESET", 102),
    ("ECONNABORTED", 103),
    ("ECONNRESET", 104),
    ("ENOBUFS", 105),
    ("EISCONN", 106),
    ("ENOTCONN", 107),
    ("ESHUTDOWN", 108),
    ("ETOOMANYREFS", 109),
    ("ETIMEDOUT", 110),
    ("ECONNREFUSED", 111),
    ("EHOSTDOWN", 112),
    ("EHOSTUNREACH", 113),
    ("EALREADY", 114),
    ("EINPROGRESS", 115),
    ("ESTALE", 116),
    ("EUCLEAN", 117),
    ("ENOTNAM", 118),
    ("ENAVAIL", 119),
    ("EISNAM", 120),
    ("EREMOTEIO", 121),
    ("EDQUOT", 122),
    ("ENOMEDIUM", 123),
    ("EMEDIUMTYPE", 124),
    ("ECANCELED", 125),
    ("ENOKEY", 126),
    ("EKEYEXPIRED", 127),
    ("EKEYREVOKED", 128),
    ("EKEYREJECTED", 129),
    ("EOWNERDEAD", 130),
    ("ENOTRECOVERABLE", 131),
    ("ERFKILL", 132),
    ("EHWPOISON", 133),
    ("EWOULDBLOCK", 11),
    ("EDEADLOCK", 35),
];
