#!/usr/bin/env python3
"""Generate the Hexagon differential-test oracle assembly (oracle.s).

The oracle is a freestanding static Hexagon ELF executed under `qemu-hexagon`
(user mode). It is the hardware-semantics reference against which the rax
software interpreter (src/backend/emulator/hexagon/) is checked.

Protocol (little-endian binary, stdin -> stdout):
  stdin:  u32 magic ('H','E','X','1' = 0x31584548)
          u32 count
          count * InCase
  stdout: u32 magic (echoed)
          u32 count (echoed)
          count * OutCase

  InCase  = u32 nwords; u32 words[4]; HexState st           (4 + 16 + 176 = 196 B)
  OutCase = HexState st; u32 trapped; u32 valid             (176 + 8     = 184 B)

  HexState (all little-endian u32, 176 bytes):
    [  0..128)  r0..r31
    [128]       pred  (P3:0 packed -> C4)
    [132]       usr   (C8)
    [136]       m0    (C6)
    [140]       m1    (C7)
    [144]       gp    (C11)
    [148]       cs0   (C12)
    [152]       cs1   (C13)
    [156]       sa0   (C0)
    [160]       lc0   (C1)
    [164]       sa1   (C2)
    [168]       lc1   (C3)
    [172]       pc    (reserved; not captured in reg-only mode)

Mechanism: each case loads the full architectural register file from g_case.st,
copies the (already-assembled, always-legal) test packet words into an
executable slot, executes the packet, and stores the resulting register file to
g_out.st. All addressing is absolute (constant-extended immediates), so no live
base pointer or scratch register is needed across the test packet -- the test
packet may freely clobber every GPR. Harness registers are saved/restored around
each case via g_hsave.
"""

import sys

NOP = 0x7F00C000

# HexState field byte offsets.
O_R = 0
O_PRED = 128
O_USR = 132
O_M0 = 136
O_M1 = 140
O_GP = 144
O_CS0 = 148
O_CS1 = 152
O_SA0 = 156
O_LC0 = 160
O_SA1 = 164
O_LC1 = 168
ST_SIZE = 176

# (control-register number, state offset). Order is irrelevant for restore
# because GPRs are loaded afterwards; r0 is the scratch and is loaded last.
CREGS = [
    (8, O_USR),
    (6, O_M0),
    (7, O_M1),
    (11, O_GP),
    (12, O_CS0),
    (13, O_CS1),
    (0, O_SA0),
    (1, O_LC0),
    (2, O_SA1),
    (3, O_LC1),
    (4, O_PRED),
]

# InCase layout.
CASE_NWORDS = 0
CASE_WORDS = 4
CASE_ST = 20
CASE_SIZE = 196
# OutCase layout.
OUT_ST = 0
OUT_TRAPPED = ST_SIZE
OUT_VALID = ST_SIZE + 4
OUT_SIZE = 184


def emit(out):
    p = lambda s="": out.append(s)

    p("// AUTO-GENERATED by tools/hexagon-diff/gen_oracle.py -- do not edit by hand.")
    p("// Hexagon differential-test oracle (runs under qemu-hexagon).")
    p(".text")
    p(".globl _start")
    p("_start:")
    # read_exact(0, g_hdr, 8); echo header.
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call write_exact }")
    # rem = count
    p("\t{ r0 = memw(##g_hdr+4) }")
    p("\t{ memw(##g_rem) = r0 }")
    p(".loop:")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ p0 = cmp.eq(r0,#0); if (p0.new) jump:nt .done }")
    # read one InCase.
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_case }")
    p(f"\t{{ r2 = #{CASE_SIZE} }}")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ call run_case }")
    # trapped = 0; valid = 1
    p("\t{ r0 = #0 }")
    p(f"\t{{ memw(##g_out+{OUT_TRAPPED}) = r0 }}")
    p("\t{ r0 = #1 }")
    p(f"\t{{ memw(##g_out+{OUT_VALID}) = r0 }}")
    # write OutCase.
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_out }")
    p(f"\t{{ r2 = #{OUT_SIZE} }}")
    p("\t{ call write_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    # rem--
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ r0 = add(r0,#-1) }")
    p("\t{ memw(##g_rem) = r0 }")
    p("\t{ jump .loop }")
    p(".done:")
    p("\t{ r0 = #0 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p(".fail:")
    p("\t{ r0 = #1 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p("")

    # ----- read_exact(r0=fd, r1=buf, r2=len) -> r0 (0 ok, -1 err) -----
    p("read_exact:")
    p("\t{ r16 = r0; r17 = r1; r18 = r2 }")
    p(".re_loop:")
    p("\t{ p0 = cmp.eq(r18,#0); if (p0.new) jump:nt .re_ok }")
    p("\t{ r0 = r16; r1 = r17; r2 = r18 }")
    p("\t{ r6 = #63 }")          # read
    p("\t{ trap0(#1) }")
    p("\t{ p0 = cmp.gt(r0,#0); if (!p0.new) jump:nt .re_err }")
    p("\t{ r17 = add(r17,r0) }")
    p("\t{ r18 = sub(r18,r0) }")
    p("\t{ jump .re_loop }")
    p(".re_ok:")
    p("\t{ r0 = #0 }")
    p("\t{ jumpr r31 }")
    p(".re_err:")
    p("\t{ r0 = #-1 }")
    p("\t{ jumpr r31 }")
    p("")

    # ----- write_exact(r0=fd, r1=buf, r2=len) -> r0 (0 ok, -1 err) -----
    p("write_exact:")
    p("\t{ r16 = r0; r17 = r1; r18 = r2 }")
    p(".we_loop:")
    p("\t{ p0 = cmp.eq(r18,#0); if (p0.new) jump:nt .we_ok }")
    p("\t{ r0 = r16; r1 = r17; r2 = r18 }")
    p("\t{ r6 = #64 }")          # write
    p("\t{ trap0(#1) }")
    p("\t{ p0 = cmp.gt(r0,#0); if (!p0.new) jump:nt .we_err }")
    p("\t{ r17 = add(r17,r0) }")
    p("\t{ r18 = sub(r18,r0) }")
    p("\t{ jump .we_loop }")
    p(".we_ok:")
    p("\t{ r0 = #0 }")
    p("\t{ jumpr r31 }")
    p(".we_err:")
    p("\t{ r0 = #-1 }")
    p("\t{ jumpr r31 }")
    p("")

    # ----- run_case -----
    p("run_case:")
    # Save all harness GPRs (r31 = caller return).
    for i in range(32):
        p(f"\t{{ memw(##g_hsave+{i*4}) = r{i} }}")
    # Copy up to 4 test words into the slot; fill the rest with NOP.
    p(f"\t{{ r5 = memw(##g_case+{CASE_NWORDS}) }}")   # nwords
    p(f"\t{{ r4 = ##{NOP:#x} }}")                     # nop filler
    for w in range(4):
        p(f"\t{{ p0 = cmp.gt(r5,#{w}) }}")
        p(f"\t{{ r3 = memw(##g_case+{CASE_WORDS + w*4}) }}")
        p("\t{ if (!p0) r3 = r4 }")
        p(f"\t{{ memw(##testslot+{w*4}) = r3 }}")
    p("\t{ isync }")
    # Install control registers (r0 = scratch).
    for creg, off in CREGS:
        p(f"\t{{ r0 = memw(##g_case+{CASE_ST + off}) }}")
        p(f"\t{{ c{creg} = r0 }}")
    # Load r1..r31 then r0 (r0 last so the scratch use above is overwritten).
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_case+{CASE_ST + O_R + i*4}) }}")
    # ---- test packet executes here ----
    p("testslot:")
    p("\t.space 16")
    # ---- capture ----
    p("epilogue:")
    for i in range(32):
        p(f"\t{{ memw(##g_out+{OUT_ST + O_R + i*4}) = r{i} }}")
    for creg, off in CREGS:
        p(f"\t{{ r0 = c{creg} }}")
        p(f"\t{{ memw(##g_out+{OUT_ST + off}) = r0 }}")
    # Restore harness GPRs (r0 last) and return.
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_hsave+{i*4}) }}")
    p("\t{ jumpr r31 }")
    p("")

    # ----- data -----
    p(".bss")
    p(".p2align 4")
    p("g_hdr:   .space 8")
    p("g_rem:   .space 4")
    p(".p2align 4")
    p(f"g_case:  .space {CASE_SIZE}")
    p(".p2align 4")
    p(f"g_out:   .space {OUT_SIZE}")
    p(".p2align 4")
    p("g_hsave: .space 128")
    p("")


def main():
    out = []
    emit(out)
    text = "\n".join(out) + "\n"
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as f:
            f.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
