#include <windows.h>
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <initializer_list>
// Original process-local working-set query oracle. All output storage is private.
using Query=LONG(NTAPI*)(HANDLE,const void*,ULONG,void*,SIZE_T,SIZE_T*);
struct Entry { uintptr_t address,flags; };
static Query query;
static LONG invoke(HANDLE h,const void* a,void* o,SIZE_T n,SIZE_T* r,ULONG* e){__try{return query(h,a,4,o,n,r);}__except(EXCEPTION_EXECUTE_HANDLER){*e=GetExceptionCode();return LONG(*e);}}
int main(){setvbuf(stdout,nullptr,_IONBF,0);auto n=GetModuleHandleW(L"ntdll.dll");query=reinterpret_cast<Query>(GetProcAddress(n,"NtQueryVirtualMemory"));if(!query)return 1;auto p=static_cast<unsigned char*>(VirtualAlloc(nullptr,32768,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE));auto reserve=VirtualAlloc(nullptr,8192,MEM_RESERVE,PAGE_READWRITE);if(!p||!reserve)return 2;auto code=GetProcAddress(n,"NtQueryVirtualMemory");printf("pointer=%zu ntdll=%p code=%p private=%p reserve=%p\n",sizeof(void*),n,code,p,reserve);DWORD old;
for(unsigned target=0;target<12;target++)for(SIZE_T len:{0u,1u,7u,8u,12u,15u,16u,17u,24u,31u,32u,64u,80u,128u}){VirtualProtect(p,32768,PAGE_READWRITE,&old);memset(p,0xa5,4096);p[12288]=0x53;p[16384]=0x74;VirtualProtect(p+16384,4096,PAGE_READWRITE|PAGE_GUARD,&old);VirtualProtect(p+20480,4096,PAGE_NOACCESS,&old);VirtualProtect(p+12288,4096,PAGE_READONLY,&old);auto e=reinterpret_cast<Entry*>(p+128);uintptr_t address=target==0?uintptr_t(n):target==1?uintptr_t(code):target==2?uintptr_t(p+8192):target==3?uintptr_t(p+12288):target==4?uintptr_t(p+16384):target==5?uintptr_t(p+20480):target==6?uintptr_t(reserve):target==7?0:target==8?1:target==9?~uintptr_t(0):target==10?uintptr_t(p+24576):uintptr_t(p+8192+1);for(unsigned i=0;i<16;i++){e[i].address=address;e[i].flags=~uintptr_t(0);}SIZE_T returned=~SIZE_T(0);ULONG ex=0;auto status=invoke(GetCurrentProcess(),nullptr,e,len,&returned,&ex);MEMORY_BASIC_INFORMATION g{};VirtualQuery(p+16384,&g,sizeof(g));printf("matrix target=%u length=%zu status=%08lX exception=%08lX returned=%zu guard=%u bytes=",target,len,status,ex,returned,unsigned((g.Protect&PAGE_GUARD)!=0));for(unsigned i=0;i<64;i++)printf("%02X",p[128+i]);printf("\n");}
for(unsigned role=0;role<30;role++){VirtualProtect(p,32768,PAGE_READWRITE,&old);memset(p,0xa5,32768);auto e=reinterpret_cast<Entry*>(p+128);for(unsigned i=0;i<16;i++){e[i].address=uintptr_t(code);e[i].flags=~uintptr_t(0);}HANDLE h=GetCurrentProcess();const void* base=nullptr;void* out=e;SIZE_T len=64;auto ret=reinterpret_cast<SIZE_T*>(p+512);switch(role){case 1:len=0;break;case 2:out=nullptr;break;case 3:out=reinterpret_cast<void*>(uintptr_t(1));break;case 4:out=p+129;break;case 5:out=p+132;break;case 6:ret=reinterpret_cast<SIZE_T*>(uintptr_t(1));break;case 7:ret=reinterpret_cast<SIZE_T*>(p+513);break;case 8:h=nullptr;break;case 9:h=reinterpret_cast<HANDLE>(intptr_t(-2));break;case 10:base=reinterpret_cast<void*>(~uintptr_t(0));break;case 11:base=code;break;case 12:out=p+4096;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 13:out=p+4096;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 14:ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 15:ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 16:out=p+4096;ret=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+4096,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 17:out=p+4096;ret=reinterpret_cast<SIZE_T*>(p+4160);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 18:ret=reinterpret_cast<SIZE_T*>(out);break;case 19:out=p+4080;len=17;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 20:out=p+4088;len=9;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 21:out=p+4080;len=16;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 22:out=p+4088;len=8;VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);break;case 23:len=0;out=reinterpret_cast<void*>(uintptr_t(1));ret=reinterpret_cast<SIZE_T*>(p+4096);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 24:out=p+4096;VirtualProtect(p+4096,4096,PAGE_READONLY,&old);break;case 25:len=sizeof(void*)*2-1;break;case 26:len=~SIZE_T(0);break;case 27:len=sizeof(void*)==4?SIZE_T(0x80000000u):SIZE_T(0x100000000ull);break;case 28:ret=nullptr;break;case 29:h=nullptr;out=nullptr;ret=nullptr;break;}
ULONG ex=0;auto status=invoke(h,base,out,len,ret,&ex);MEMORY_BASIC_INFORMATION a{},b{};VirtualQuery(p+4096,&a,sizeof(a));VirtualQuery(p+8192,&b,sizeof(b));printf("fault role=%u length=%zu status=%08lX exception=%08lX guards=%u%u bytes=",role,len,status,ex,unsigned((a.Protect&PAGE_GUARD)!=0),unsigned((b.Protect&PAGE_GUARD)!=0));for(unsigned i=0;i<64;i++)printf("%02X",p[128+i]);printf(" returned=");for(unsigned i=512;i<528;i++)printf("%02X",p[i]);printf("\n");}
for(DWORD access:{0x10u,0x400u,0x1000u,0x1010u,0x410u,unsigned(PROCESS_ALL_ACCESS)}){VirtualProtect(p,32768,PAGE_READWRITE,&old);memset(p,0xa5,32768);auto e=reinterpret_cast<Entry*>(p+128);e->address=uintptr_t(code);auto h=OpenProcess(access,FALSE,GetCurrentProcessId());if(!h){printf("handle access=%lX error=%lu\n",access,GetLastError());continue;}SIZE_T r=~SIZE_T(0);ULONG ex=0;auto s=invoke(h,nullptr,e,sizeof(Entry),&r,&ex);printf("rights access=%lX status=%08lX exception=%08lX returned=%zu flags=%llX\n",access,s,ex,r,static_cast<unsigned long long>(e->flags));CloseHandle(h);}
VirtualFree(reserve,0,MEM_RELEASE);VirtualFree(p,0,MEM_RELEASE);return 0;}
