#include <windows.h>
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <initializer_list>
using Query=LONG(NTAPI*)(HANDLE,const void*,ULONG,void*,SIZE_T,SIZE_T*);
struct Entry { uintptr_t address,flags; };
static Query query;
static LONG invoke(HANDLE h,const void* a,void* o,SIZE_T n,SIZE_T* r,ULONG* e){__try{return query(h,a,4,o,n,r);}__except(EXCEPTION_EXECUTE_HANDLER){*e=GetExceptionCode();return LONG(*e);}}
// Original process-local capture-order oracle; protects only its own scratch.
int main(){setvbuf(stdout,nullptr,_IONBF,0);auto n=GetModuleHandleW(L"ntdll.dll");auto code=GetProcAddress(n,"NtQueryVirtualMemory");query=reinterpret_cast<Query>(code);auto p=static_cast<unsigned char*>(VirtualAlloc(nullptr,24576,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE));if(!p||!query)return 1;DWORD old;printf("pointer=%zu code=%p\n",sizeof(void*),code);
for(unsigned role=0;role<24;role++){VirtualProtect(p,24576,PAGE_READWRITE,&old);memset(p,0xa5,24576);auto e=reinterpret_cast<Entry*>(p+4096);for(unsigned i=0;i<16;i++){e[i].address=uintptr_t(code);e[i].flags=~uintptr_t(0);}HANDLE h=GetCurrentProcess();const void* base=nullptr;void* out=e;SIZE_T len=64;auto ret=reinterpret_cast<SIZE_T*>(p+128);switch(role){case 0:VirtualProtect(p+4096,4096,PAGE_READONLY,&old);h=nullptr;break;case 1:VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);h=nullptr;break;case 2:out=nullptr;h=nullptr;break;case 3:out=reinterpret_cast<void*>(uintptr_t(1));h=nullptr;break;case 4:VirtualProtect(p+4096,4096,PAGE_NOACCESS,&old);h=nullptr;break;case 5:ret=reinterpret_cast<SIZE_T*>(p+4160);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 6:ret=reinterpret_cast<SIZE_T*>(out);VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 7:ret=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+4096,8192,PAGE_READWRITE|PAGE_GUARD,&old);break;case 8:ret=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+8192,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 9:len=0;VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);ret=reinterpret_cast<SIZE_T*>(p+8192);VirtualProtect(p+8192,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 10:base=reinterpret_cast<void*>(~uintptr_t(0));VirtualProtect(p+4096,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 11:base=reinterpret_cast<void*>(~uintptr_t(0));out=nullptr;break;case 12:out=nullptr;len=0;break;case 13:out=p+4097;h=nullptr;break;case 14:len=0;h=nullptr;break;case 15:VirtualProtect(p+4096,4096,PAGE_READONLY,&old);break;case 16:ret=nullptr;break;case 17:out=p+8192-sizeof(Entry);e=reinterpret_cast<Entry*>(out);e[0].address=uintptr_t(code);len=sizeof(Entry)+1;VirtualProtect(p+8192,4096,PAGE_NOACCESS,&old);break;case 18:out=p+8192-sizeof(Entry);e=reinterpret_cast<Entry*>(out);e[0].address=uintptr_t(code);len=sizeof(Entry)+1;VirtualProtect(p+8192,4096,PAGE_READWRITE|PAGE_GUARD,&old);break;case 19:ret=reinterpret_cast<SIZE_T*>(p+8190);VirtualProtect(p+8192,4096,PAGE_NOACCESS,&old);break;case 20:out=e;ret=reinterpret_cast<SIZE_T*>(reinterpret_cast<char*>(out)+sizeof(void*));break;case 21:e[0].address=uintptr_t(out);break;case 22:VirtualProtect(p+12288,4096,PAGE_READWRITE|PAGE_GUARD,&old);e[0].address=uintptr_t(p+12288);break;case 23:p[12288]=1;VirtualProtect(p+12288,4096,PAGE_NOACCESS,&old);e[0].address=uintptr_t(p+12288);break;}
ULONG ex=0;auto s=invoke(h,base,out,len,ret,&ex);MEMORY_BASIC_INFORMATION a{},b{},c{};VirtualQuery(p+4096,&a,sizeof(a));VirtualQuery(p+8192,&b,sizeof(b));VirtualQuery(p+12288,&c,sizeof(c));printf("capture role=%u length=%zu status=%08lX exception=%08lX guards=%u%u%u output=",role,len,s,ex,unsigned((a.Protect&PAGE_GUARD)!=0),unsigned((b.Protect&PAGE_GUARD)!=0),unsigned((c.Protect&PAGE_GUARD)!=0));VirtualProtect(p,24576,PAGE_READWRITE,&old);if(out&&uintptr_t(out)>=uintptr_t(p)&&uintptr_t(out)+64<=uintptr_t(p)+24576){for(unsigned i=0;i<64;i++)printf("%02X",reinterpret_cast<unsigned char*>(out)[i]);}printf(" returned=");if(ret){for(unsigned i=0;i<16;i++)printf("%02X",reinterpret_cast<unsigned char*>(ret)[i]);}printf("\n");}
VirtualFree(p,0,MEM_RELEASE);return 0;}
