// @generated by tools/darwin/gen_mig.py from XNU 12377.121.6
// (docs/specifications/darwin/xnu-12377.121.6). Do not edit by hand.

//! MIG message IDs of the kernel's subsystems (`msgh_id` of each
//! routine's request; its reply's is 100 more).

/// `clock.defs` (subsystem 1000).
pub mod clock {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 1000;
    /// `clock_get_time`.
    pub const CLOCK_GET_TIME: i32 = 1000;
    /// `clock_get_attributes`.
    pub const CLOCK_GET_ATTRIBUTES: i32 = 1001;
    /// `clock_alarm`.
    pub const CLOCK_ALARM: i32 = 1002;
}

/// `mach_host.defs` (subsystem 200).
pub mod host {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 200;
    /// `host_info`.
    pub const HOST_INFO: i32 = 200;
    /// `host_kernel_version`.
    pub const HOST_KERNEL_VERSION: i32 = 201;
    /// `_host_page_size`.
    pub const HOST_PAGE_SIZE: i32 = 202;
    /// `mach_memory_object_memory_entry`.
    pub const MACH_MEMORY_OBJECT_MEMORY_ENTRY: i32 = 203;
    /// `host_processor_info`.
    pub const HOST_PROCESSOR_INFO: i32 = 204;
    /// `host_get_io_main`.
    pub const HOST_GET_IO_MAIN: i32 = 205;
    /// `host_get_clock_service`.
    pub const HOST_GET_CLOCK_SERVICE: i32 = 206;
    /// `kmod_get_info`.
    pub const KMOD_GET_INFO: i32 = 207;
    /// `host_virtual_physical_table_info`.
    pub const HOST_VIRTUAL_PHYSICAL_TABLE_INFO: i32 = 209;
    /// `processor_set_default`.
    pub const PROCESSOR_SET_DEFAULT: i32 = 213;
    /// `processor_set_create`.
    pub const PROCESSOR_SET_CREATE: i32 = 214;
    /// `mach_memory_object_memory_entry_64`.
    pub const MACH_MEMORY_OBJECT_MEMORY_ENTRY_64: i32 = 215;
    /// `host_statistics`.
    pub const HOST_STATISTICS: i32 = 216;
    /// `host_request_notification`.
    pub const HOST_REQUEST_NOTIFICATION: i32 = 217;
    /// `host_lockgroup_info`.
    pub const HOST_LOCKGROUP_INFO: i32 = 218;
    /// `host_statistics64`.
    pub const HOST_STATISTICS64: i32 = 219;
    /// `mach_zone_info`.
    pub const MACH_ZONE_INFO: i32 = 220;
    /// `_kernelrpc_host_create_mach_voucher`.
    pub const KERNELRPC_HOST_CREATE_MACH_VOUCHER: i32 = 222;
    /// `host_register_mach_voucher_attr_manager`.
    pub const HOST_REGISTER_MACH_VOUCHER_ATTR_MANAGER: i32 = 223;
    /// `host_register_well_known_mach_voucher_attr_manager`.
    pub const HOST_REGISTER_WELL_KNOWN_MACH_VOUCHER_ATTR_MANAGER: i32 = 224;
    /// `host_set_atm_diagnostic_flag`.
    pub const HOST_SET_ATM_DIAGNOSTIC_FLAG: i32 = 225;
    /// `mach_memory_info`.
    pub const MACH_MEMORY_INFO: i32 = 227;
    /// `host_set_multiuser_config_flags`.
    pub const HOST_SET_MULTIUSER_CONFIG_FLAGS: i32 = 228;
    /// `mach_zone_info_for_zone`.
    pub const MACH_ZONE_INFO_FOR_ZONE: i32 = 231;
    /// `mach_memory_info_redacted`.
    pub const MACH_MEMORY_INFO_REDACTED: i32 = 235;
}

/// `host_priv.defs` (subsystem 400).
pub mod host_priv {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 400;
    /// `host_get_boot_info`.
    pub const HOST_GET_BOOT_INFO: i32 = 400;
    /// `host_reboot`.
    pub const HOST_REBOOT: i32 = 401;
    /// `host_priv_statistics`.
    pub const HOST_PRIV_STATISTICS: i32 = 402;
    /// `host_default_memory_manager`.
    pub const HOST_DEFAULT_MEMORY_MANAGER: i32 = 403;
    /// `vm_wire`.
    pub const VM_WIRE: i32 = 404;
    /// `thread_wire`.
    pub const THREAD_WIRE: i32 = 405;
    /// `vm_allocate_cpm`.
    pub const VM_ALLOCATE_CPM: i32 = 406;
    /// `host_processors`.
    pub const HOST_PROCESSORS: i32 = 407;
    /// `host_get_clock_control`.
    pub const HOST_GET_CLOCK_CONTROL: i32 = 408;
    /// `kmod_create`.
    pub const KMOD_CREATE: i32 = 409;
    /// `kmod_destroy`.
    pub const KMOD_DESTROY: i32 = 410;
    /// `kmod_control`.
    pub const KMOD_CONTROL: i32 = 411;
    /// `host_get_special_port`.
    pub const HOST_GET_SPECIAL_PORT: i32 = 412;
    /// `host_set_special_port`.
    pub const HOST_SET_SPECIAL_PORT: i32 = 413;
    /// `host_set_exception_ports`.
    pub const HOST_SET_EXCEPTION_PORTS: i32 = 414;
    /// `host_get_exception_ports`.
    pub const HOST_GET_EXCEPTION_PORTS: i32 = 415;
    /// `host_swap_exception_ports`.
    pub const HOST_SWAP_EXCEPTION_PORTS: i32 = 416;
    /// `mach_vm_wire`.
    pub const MACH_VM_WIRE: i32 = 418;
    /// `host_processor_sets`.
    pub const HOST_PROCESSOR_SETS: i32 = 419;
    /// `host_processor_set_priv`.
    pub const HOST_PROCESSOR_SET_PRIV: i32 = 420;
    /// `host_set_UNDServer`.
    pub const HOST_SET_UNDSERVER: i32 = 423;
    /// `host_get_UNDServer`.
    pub const HOST_GET_UNDSERVER: i32 = 424;
    /// `kext_request`.
    pub const KEXT_REQUEST: i32 = 425;
}

/// `mach_port.defs` (subsystem 3200).
pub mod mach_port {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 3200;
    /// `mach_port_names`.
    pub const MACH_PORT_NAMES: i32 = 3200;
    /// `mach_port_type`.
    pub const MACH_PORT_TYPE: i32 = 3201;
    /// `mach_port_rename`.
    pub const MACH_PORT_RENAME: i32 = 3202;
    /// `mach_port_allocate_name`.
    pub const MACH_PORT_ALLOCATE_NAME: i32 = 3203;
    /// `mach_port_allocate`.
    pub const MACH_PORT_ALLOCATE: i32 = 3204;
    /// `mach_port_destroy`.
    pub const MACH_PORT_DESTROY: i32 = 3205;
    /// `mach_port_deallocate`.
    pub const MACH_PORT_DEALLOCATE: i32 = 3206;
    /// `mach_port_get_refs`.
    pub const MACH_PORT_GET_REFS: i32 = 3207;
    /// `mach_port_mod_refs`.
    pub const MACH_PORT_MOD_REFS: i32 = 3208;
    /// `mach_port_peek`.
    pub const MACH_PORT_PEEK: i32 = 3209;
    /// `mach_port_set_mscount`.
    pub const MACH_PORT_SET_MSCOUNT: i32 = 3210;
    /// `mach_port_get_set_status`.
    pub const MACH_PORT_GET_SET_STATUS: i32 = 3211;
    /// `mach_port_move_member`.
    pub const MACH_PORT_MOVE_MEMBER: i32 = 3212;
    /// `mach_port_request_notification`.
    pub const MACH_PORT_REQUEST_NOTIFICATION: i32 = 3213;
    /// `mach_port_insert_right`.
    pub const MACH_PORT_INSERT_RIGHT: i32 = 3214;
    /// `mach_port_extract_right`.
    pub const MACH_PORT_EXTRACT_RIGHT: i32 = 3215;
    /// `mach_port_set_seqno`.
    pub const MACH_PORT_SET_SEQNO: i32 = 3216;
    /// `mach_port_get_attributes`.
    pub const MACH_PORT_GET_ATTRIBUTES: i32 = 3217;
    /// `mach_port_set_attributes`.
    pub const MACH_PORT_SET_ATTRIBUTES: i32 = 3218;
    /// `mach_port_allocate_qos`.
    pub const MACH_PORT_ALLOCATE_QOS: i32 = 3219;
    /// `mach_port_allocate_full`.
    pub const MACH_PORT_ALLOCATE_FULL: i32 = 3220;
    /// `task_set_port_space`.
    pub const TASK_SET_PORT_SPACE: i32 = 3221;
    /// `mach_port_get_srights`.
    pub const MACH_PORT_GET_SRIGHTS: i32 = 3222;
    /// `mach_port_space_info`.
    pub const MACH_PORT_SPACE_INFO: i32 = 3223;
    /// `mach_port_dnrequest_info`.
    pub const MACH_PORT_DNREQUEST_INFO: i32 = 3224;
    /// `mach_port_kernel_object`.
    pub const MACH_PORT_KERNEL_OBJECT: i32 = 3225;
    /// `mach_port_insert_member`.
    pub const MACH_PORT_INSERT_MEMBER: i32 = 3226;
    /// `mach_port_extract_member`.
    pub const MACH_PORT_EXTRACT_MEMBER: i32 = 3227;
    /// `mach_port_get_context`.
    pub const MACH_PORT_GET_CONTEXT: i32 = 3228;
    /// `mach_port_set_context`.
    pub const MACH_PORT_SET_CONTEXT: i32 = 3229;
    /// `mach_port_kobject`.
    pub const MACH_PORT_KOBJECT: i32 = 3230;
    /// `mach_port_construct`.
    pub const MACH_PORT_CONSTRUCT: i32 = 3231;
    /// `mach_port_destruct`.
    pub const MACH_PORT_DESTRUCT: i32 = 3232;
    /// `mach_port_guard`.
    pub const MACH_PORT_GUARD: i32 = 3233;
    /// `mach_port_unguard`.
    pub const MACH_PORT_UNGUARD: i32 = 3234;
    /// `mach_port_space_basic_info`.
    pub const MACH_PORT_SPACE_BASIC_INFO: i32 = 3235;
    /// `mach_port_special_reply_port_reset_link`.
    pub const MACH_PORT_SPECIAL_REPLY_PORT_RESET_LINK: i32 = 3236;
    /// `mach_port_guard_with_flags`.
    pub const MACH_PORT_GUARD_WITH_FLAGS: i32 = 3237;
    /// `mach_port_swap_guard`.
    pub const MACH_PORT_SWAP_GUARD: i32 = 3238;
    /// `mach_port_kobject_description`.
    pub const MACH_PORT_KOBJECT_DESCRIPTION: i32 = 3239;
    /// `mach_port_is_connection_for_service`.
    pub const MACH_PORT_IS_CONNECTION_FOR_SERVICE: i32 = 3240;
    /// `mach_port_get_service_port_info`.
    pub const MACH_PORT_GET_SERVICE_PORT_INFO: i32 = 3241;
    /// `mach_port_assert_attributes`.
    pub const MACH_PORT_ASSERT_ATTRIBUTES: i32 = 3242;
}

/// `mach_vm.defs` (subsystem 4800).
pub mod mach_vm {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 4800;
    /// `_kernelrpc_mach_vm_allocate`.
    pub const KERNELRPC_MACH_VM_ALLOCATE: i32 = 4800;
    /// `_kernelrpc_mach_vm_deallocate`.
    pub const KERNELRPC_MACH_VM_DEALLOCATE: i32 = 4801;
    /// `_kernelrpc_mach_vm_protect`.
    pub const KERNELRPC_MACH_VM_PROTECT: i32 = 4802;
    /// `mach_vm_inherit`.
    pub const MACH_VM_INHERIT: i32 = 4803;
    /// `_kernelrpc_mach_vm_read`.
    pub const KERNELRPC_MACH_VM_READ: i32 = 4804;
    /// `mach_vm_read_list`.
    pub const MACH_VM_READ_LIST: i32 = 4805;
    /// `mach_vm_write`.
    pub const MACH_VM_WRITE: i32 = 4806;
    /// `mach_vm_copy`.
    pub const MACH_VM_COPY: i32 = 4807;
    /// `mach_vm_read_overwrite`.
    pub const MACH_VM_READ_OVERWRITE: i32 = 4808;
    /// `mach_vm_msync`.
    pub const MACH_VM_MSYNC: i32 = 4809;
    /// `mach_vm_behavior_set`.
    pub const MACH_VM_BEHAVIOR_SET: i32 = 4810;
    /// `_kernelrpc_mach_vm_map`.
    pub const KERNELRPC_MACH_VM_MAP: i32 = 4811;
    /// `mach_vm_machine_attribute`.
    pub const MACH_VM_MACHINE_ATTRIBUTE: i32 = 4812;
    /// `_kernelrpc_mach_vm_remap`.
    pub const KERNELRPC_MACH_VM_REMAP: i32 = 4813;
    /// `mach_vm_page_query`.
    pub const MACH_VM_PAGE_QUERY: i32 = 4814;
    /// `mach_vm_region_recurse`.
    pub const MACH_VM_REGION_RECURSE: i32 = 4815;
    /// `mach_vm_region`.
    pub const MACH_VM_REGION: i32 = 4816;
    /// `mach_make_memory_entry`.
    pub const MACH_MAKE_MEMORY_ENTRY: i32 = 4817;
    /// `_kernelrpc_mach_vm_purgable_control`.
    pub const KERNELRPC_MACH_VM_PURGABLE_CONTROL: i32 = 4818;
    /// `mach_vm_page_info`.
    pub const MACH_VM_PAGE_INFO: i32 = 4819;
    /// `mach_vm_page_range_query`.
    pub const MACH_VM_PAGE_RANGE_QUERY: i32 = 4820;
    /// `_kernelrpc_mach_vm_remap_new`.
    pub const KERNELRPC_MACH_VM_REMAP_NEW: i32 = 4821;
    /// `mach_vm_deferred_reclamation_buffer_allocate`.
    pub const MACH_VM_DEFERRED_RECLAMATION_BUFFER_ALLOCATE: i32 = 4822;
    /// `mach_vm_deferred_reclamation_buffer_flush`.
    pub const MACH_VM_DEFERRED_RECLAMATION_BUFFER_FLUSH: i32 = 4823;
    /// `mach_vm_range_create`.
    pub const MACH_VM_RANGE_CREATE: i32 = 4825;
    /// `mach_vm_deferred_reclamation_buffer_resize`.
    pub const MACH_VM_DEFERRED_RECLAMATION_BUFFER_RESIZE: i32 = 4826;
    /// `_kernelrpc_mach_vm_update_pointers_with_remote_tags`.
    pub const KERNELRPC_MACH_VM_UPDATE_POINTERS_WITH_REMOTE_TAGS: i32 = 4827;
    /// `mach_vm_deferred_reclamation_buffer_query`.
    pub const MACH_VM_DEFERRED_RECLAMATION_BUFFER_QUERY: i32 = 4828;
    /// `_kernelrpc_mach_vm_reallocate`.
    pub const KERNELRPC_MACH_VM_REALLOCATE: i32 = 4829;
}

/// `mach_voucher.defs` (subsystem 5400).
pub mod mach_voucher {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 5400;
    /// `mach_voucher_extract_attr_content`.
    pub const MACH_VOUCHER_EXTRACT_ATTR_CONTENT: i32 = 5400;
    /// `_kernelrpc_mach_voucher_extract_attr_recipe`.
    pub const KERNELRPC_MACH_VOUCHER_EXTRACT_ATTR_RECIPE: i32 = 5401;
    /// `mach_voucher_extract_all_attr_recipes`.
    pub const MACH_VOUCHER_EXTRACT_ALL_ATTR_RECIPES: i32 = 5402;
    /// `mach_voucher_attr_command`.
    pub const MACH_VOUCHER_ATTR_COMMAND: i32 = 5403;
    /// `mach_voucher_debug_info`.
    pub const MACH_VOUCHER_DEBUG_INFO: i32 = 5404;
}

/// `memory_entry.defs` (subsystem 4900).
pub mod memory_entry {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 4900;
    /// `mach_memory_entry_purgable_control`.
    pub const MACH_MEMORY_ENTRY_PURGABLE_CONTROL: i32 = 4900;
    /// `mach_memory_entry_access_tracking`.
    pub const MACH_MEMORY_ENTRY_ACCESS_TRACKING: i32 = 4901;
    /// `mach_memory_entry_ownership`.
    pub const MACH_MEMORY_ENTRY_OWNERSHIP: i32 = 4902;
    /// `mach_memory_entry_get_page_counts`.
    pub const MACH_MEMORY_ENTRY_GET_PAGE_COUNTS: i32 = 4903;
}

/// `processor_set.defs` (subsystem 4000).
pub mod processor_set {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 4000;
    /// `processor_set_statistics`.
    pub const PROCESSOR_SET_STATISTICS: i32 = 4000;
    /// `processor_set_destroy`.
    pub const PROCESSOR_SET_DESTROY: i32 = 4001;
    /// `processor_set_max_priority`.
    pub const PROCESSOR_SET_MAX_PRIORITY: i32 = 4002;
    /// `processor_set_policy_enable`.
    pub const PROCESSOR_SET_POLICY_ENABLE: i32 = 4003;
    /// `processor_set_policy_disable`.
    pub const PROCESSOR_SET_POLICY_DISABLE: i32 = 4004;
    /// `processor_set_tasks`.
    pub const PROCESSOR_SET_TASKS: i32 = 4005;
    /// `processor_set_threads`.
    pub const PROCESSOR_SET_THREADS: i32 = 4006;
    /// `processor_set_policy_control`.
    pub const PROCESSOR_SET_POLICY_CONTROL: i32 = 4007;
    /// `processor_set_stack_usage`.
    pub const PROCESSOR_SET_STACK_USAGE: i32 = 4008;
    /// `processor_set_info`.
    pub const PROCESSOR_SET_INFO: i32 = 4009;
    /// `processor_set_tasks_with_flavor`.
    pub const PROCESSOR_SET_TASKS_WITH_FLAVOR: i32 = 4010;
}

/// `restartable.defs` (subsystem 8000).
pub mod task_restartable {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 8000;
    /// `task_restartable_ranges_register`.
    pub const TASK_RESTARTABLE_RANGES_REGISTER: i32 = 8000;
    /// `task_restartable_ranges_synchronize`.
    pub const TASK_RESTARTABLE_RANGES_SYNCHRONIZE: i32 = 8001;
}

/// `semaphore.defs` (subsystem 617200).
pub mod semaphore {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 617200;
    /// `semaphore_signal`.
    pub const SEMAPHORE_SIGNAL: i32 = 617200;
    /// `semaphore_signal_all`.
    pub const SEMAPHORE_SIGNAL_ALL: i32 = 617201;
    /// `semaphore_wait`.
    pub const SEMAPHORE_WAIT: i32 = 617202;
    /// `semaphore_signal_thread`.
    pub const SEMAPHORE_SIGNAL_THREAD: i32 = 617203;
    /// `semaphore_timedwait`.
    pub const SEMAPHORE_TIMEDWAIT: i32 = 617204;
    /// `semaphore_wait_signal`.
    pub const SEMAPHORE_WAIT_SIGNAL: i32 = 617205;
    /// `semaphore_timedwait_signal`.
    pub const SEMAPHORE_TIMEDWAIT_SIGNAL: i32 = 617206;
}

/// `task.defs` (subsystem 3400).
pub mod task {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 3400;
    /// `task_create`.
    pub const TASK_CREATE: i32 = 3400;
    /// `task_terminate`.
    pub const TASK_TERMINATE: i32 = 3401;
    /// `task_threads`.
    pub const TASK_THREADS: i32 = 3402;
    /// `_kernelrpc_mach_ports_register3`.
    pub const KERNELRPC_MACH_PORTS_REGISTER3: i32 = 3403;
    /// `_kernelrpc_mach_ports_lookup3`.
    pub const KERNELRPC_MACH_PORTS_LOOKUP3: i32 = 3404;
    /// `task_info`.
    pub const TASK_INFO: i32 = 3405;
    /// `task_set_info`.
    pub const TASK_SET_INFO: i32 = 3406;
    /// `task_suspend`.
    pub const TASK_SUSPEND: i32 = 3407;
    /// `task_resume`.
    pub const TASK_RESUME: i32 = 3408;
    /// `task_get_special_port`.
    pub const TASK_GET_SPECIAL_PORT: i32 = 3409;
    /// `task_set_special_port`.
    pub const TASK_SET_SPECIAL_PORT: i32 = 3410;
    /// `thread_create`.
    pub const THREAD_CREATE: i32 = 3411;
    /// `thread_create_running`.
    pub const THREAD_CREATE_RUNNING: i32 = 3412;
    /// `task_set_exception_ports`.
    pub const TASK_SET_EXCEPTION_PORTS: i32 = 3413;
    /// `task_get_exception_ports`.
    pub const TASK_GET_EXCEPTION_PORTS: i32 = 3414;
    /// `task_swap_exception_ports`.
    pub const TASK_SWAP_EXCEPTION_PORTS: i32 = 3415;
    /// `lock_set_create`.
    pub const LOCK_SET_CREATE: i32 = 3416;
    /// `lock_set_destroy`.
    pub const LOCK_SET_DESTROY: i32 = 3417;
    /// `semaphore_create`.
    pub const SEMAPHORE_CREATE: i32 = 3418;
    /// `semaphore_destroy`.
    pub const SEMAPHORE_DESTROY: i32 = 3419;
    /// `task_policy_set`.
    pub const TASK_POLICY_SET: i32 = 3420;
    /// `task_policy_get`.
    pub const TASK_POLICY_GET: i32 = 3421;
    /// `task_sample`.
    pub const TASK_SAMPLE: i32 = 3422;
    /// `task_policy`.
    pub const TASK_POLICY: i32 = 3423;
    /// `task_set_emulation`.
    pub const TASK_SET_EMULATION: i32 = 3424;
    /// `task_get_emulation_vector`.
    pub const TASK_GET_EMULATION_VECTOR: i32 = 3425;
    /// `task_set_emulation_vector`.
    pub const TASK_SET_EMULATION_VECTOR: i32 = 3426;
    /// `task_set_ras_pc`.
    pub const TASK_SET_RAS_PC: i32 = 3427;
    /// `task_zone_info`.
    pub const TASK_ZONE_INFO: i32 = 3428;
    /// `task_assign`.
    pub const TASK_ASSIGN: i32 = 3429;
    /// `task_assign_default`.
    pub const TASK_ASSIGN_DEFAULT: i32 = 3430;
    /// `task_get_assignment`.
    pub const TASK_GET_ASSIGNMENT: i32 = 3431;
    /// `task_set_policy`.
    pub const TASK_SET_POLICY: i32 = 3432;
    /// `task_get_state`.
    pub const TASK_GET_STATE: i32 = 3433;
    /// `task_set_state`.
    pub const TASK_SET_STATE: i32 = 3434;
    /// `task_set_phys_footprint_limit`.
    pub const TASK_SET_PHYS_FOOTPRINT_LIMIT: i32 = 3435;
    /// `task_suspend2`.
    pub const TASK_SUSPEND2: i32 = 3436;
    /// `task_resume2`.
    pub const TASK_RESUME2: i32 = 3437;
    /// `task_purgable_info`.
    pub const TASK_PURGABLE_INFO: i32 = 3438;
    /// `task_get_mach_voucher`.
    pub const TASK_GET_MACH_VOUCHER: i32 = 3439;
    /// `task_set_mach_voucher`.
    pub const TASK_SET_MACH_VOUCHER: i32 = 3440;
    /// `task_swap_mach_voucher`.
    pub const TASK_SWAP_MACH_VOUCHER: i32 = 3441;
    /// `task_generate_corpse`.
    pub const TASK_GENERATE_CORPSE: i32 = 3442;
    /// `task_map_corpse_info`.
    pub const TASK_MAP_CORPSE_INFO: i32 = 3443;
    /// `task_register_dyld_image_infos`.
    pub const TASK_REGISTER_DYLD_IMAGE_INFOS: i32 = 3444;
    /// `task_unregister_dyld_image_infos`.
    pub const TASK_UNREGISTER_DYLD_IMAGE_INFOS: i32 = 3445;
    /// `task_get_dyld_image_infos`.
    pub const TASK_GET_DYLD_IMAGE_INFOS: i32 = 3446;
    /// `task_register_dyld_shared_cache_image_info`.
    pub const TASK_REGISTER_DYLD_SHARED_CACHE_IMAGE_INFO: i32 = 3447;
    /// `task_register_dyld_set_dyld_state`.
    pub const TASK_REGISTER_DYLD_SET_DYLD_STATE: i32 = 3448;
    /// `task_register_dyld_get_process_state`.
    pub const TASK_REGISTER_DYLD_GET_PROCESS_STATE: i32 = 3449;
    /// `task_map_corpse_info_64`.
    pub const TASK_MAP_CORPSE_INFO_64: i32 = 3450;
    /// `task_inspect`.
    pub const TASK_INSPECT: i32 = 3451;
    /// `task_get_exc_guard_behavior`.
    pub const TASK_GET_EXC_GUARD_BEHAVIOR: i32 = 3452;
    /// `task_set_exc_guard_behavior`.
    pub const TASK_SET_EXC_GUARD_BEHAVIOR: i32 = 3453;
    /// `_kernelrpc_mach_task_is_self`.
    pub const KERNELRPC_MACH_TASK_IS_SELF: i32 = 3455;
    /// `task_dyld_process_info_notify_register`.
    pub const TASK_DYLD_PROCESS_INFO_NOTIFY_REGISTER: i32 = 3456;
    /// `task_create_identity_token`.
    pub const TASK_CREATE_IDENTITY_TOKEN: i32 = 3457;
    /// `task_identity_token_get_task_port`.
    pub const TASK_IDENTITY_TOKEN_GET_TASK_PORT: i32 = 3458;
    /// `task_dyld_process_info_notify_deregister`.
    pub const TASK_DYLD_PROCESS_INFO_NOTIFY_DEREGISTER: i32 = 3459;
    /// `task_get_exception_ports_info`.
    pub const TASK_GET_EXCEPTION_PORTS_INFO: i32 = 3460;
    /// `task_test_sync_upcall`.
    pub const TASK_TEST_SYNC_UPCALL: i32 = 3461;
    /// `task_set_corpse_forking_behavior`.
    pub const TASK_SET_CORPSE_FORKING_BEHAVIOR: i32 = 3462;
    /// `task_test_async_upcall_propagation`.
    pub const TASK_TEST_ASYNC_UPCALL_PROPAGATION: i32 = 3463;
    /// `task_map_kcdata_object_64`.
    pub const TASK_MAP_KCDATA_OBJECT_64: i32 = 3464;
    /// `task_register_hardened_exception_handler`.
    pub const TASK_REGISTER_HARDENED_EXCEPTION_HANDLER: i32 = 3465;
}

/// `thread_act.defs` (subsystem 3600).
pub mod thread_act {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 3600;
    /// `thread_terminate`.
    pub const THREAD_TERMINATE: i32 = 3600;
    /// `act_get_state`.
    pub const ACT_GET_STATE: i32 = 3601;
    /// `act_set_state`.
    pub const ACT_SET_STATE: i32 = 3602;
    /// `thread_get_state`.
    pub const THREAD_GET_STATE: i32 = 3603;
    /// `thread_set_state`.
    pub const THREAD_SET_STATE: i32 = 3604;
    /// `thread_suspend`.
    pub const THREAD_SUSPEND: i32 = 3605;
    /// `thread_resume`.
    pub const THREAD_RESUME: i32 = 3606;
    /// `thread_abort`.
    pub const THREAD_ABORT: i32 = 3607;
    /// `thread_abort_safely`.
    pub const THREAD_ABORT_SAFELY: i32 = 3608;
    /// `thread_depress_abort`.
    pub const THREAD_DEPRESS_ABORT: i32 = 3609;
    /// `thread_get_special_port`.
    pub const THREAD_GET_SPECIAL_PORT: i32 = 3610;
    /// `thread_set_special_port`.
    pub const THREAD_SET_SPECIAL_PORT: i32 = 3611;
    /// `thread_info`.
    pub const THREAD_INFO: i32 = 3612;
    /// `thread_set_exception_ports`.
    pub const THREAD_SET_EXCEPTION_PORTS: i32 = 3613;
    /// `thread_get_exception_ports`.
    pub const THREAD_GET_EXCEPTION_PORTS: i32 = 3614;
    /// `thread_swap_exception_ports`.
    pub const THREAD_SWAP_EXCEPTION_PORTS: i32 = 3615;
    /// `_kernelrpc_thread_policy`.
    pub const KERNELRPC_THREAD_POLICY: i32 = 3616;
    /// `_kernelrpc_thread_policy_set`.
    pub const KERNELRPC_THREAD_POLICY_SET: i32 = 3617;
    /// `thread_policy_get`.
    pub const THREAD_POLICY_GET: i32 = 3618;
    /// `thread_sample`.
    pub const THREAD_SAMPLE: i32 = 3619;
    /// `etap_trace_thread`.
    pub const ETAP_TRACE_THREAD: i32 = 3620;
    /// `thread_assign`.
    pub const THREAD_ASSIGN: i32 = 3621;
    /// `thread_assign_default`.
    pub const THREAD_ASSIGN_DEFAULT: i32 = 3622;
    /// `thread_get_assignment`.
    pub const THREAD_GET_ASSIGNMENT: i32 = 3623;
    /// `_kernelrpc_thread_set_policy`.
    pub const KERNELRPC_THREAD_SET_POLICY: i32 = 3624;
    /// `thread_get_mach_voucher`.
    pub const THREAD_GET_MACH_VOUCHER: i32 = 3625;
    /// `thread_set_mach_voucher`.
    pub const THREAD_SET_MACH_VOUCHER: i32 = 3626;
    /// `thread_swap_mach_voucher`.
    pub const THREAD_SWAP_MACH_VOUCHER: i32 = 3627;
    /// `thread_convert_thread_state`.
    pub const THREAD_CONVERT_THREAD_STATE: i32 = 3628;
    /// `thread_get_exception_ports_info`.
    pub const THREAD_GET_EXCEPTION_PORTS_INFO: i32 = 3630;
    /// `thread_adopt_exception_handler`.
    pub const THREAD_ADOPT_EXCEPTION_HANDLER: i32 = 3631;
    /// `thread_suspend2`.
    pub const THREAD_SUSPEND2: i32 = 3632;
    /// `thread_resume2`.
    pub const THREAD_RESUME2: i32 = 3633;
}

/// `vm_map.defs` (subsystem 3800).
pub mod vm_map {
    /// The subsystem's first message ID.
    pub const BASE: i32 = 3800;
    /// `vm_region`.
    pub const VM_REGION: i32 = 3800;
    /// `vm_inherit`.
    pub const VM_INHERIT: i32 = 3804;
    /// `_kernelrpc_vm_read`.
    pub const KERNELRPC_VM_READ: i32 = 3805;
    /// `vm_read_list`.
    pub const VM_READ_LIST: i32 = 3806;
    /// `vm_write`.
    pub const VM_WRITE: i32 = 3807;
    /// `vm_copy`.
    pub const VM_COPY: i32 = 3808;
    /// `vm_read_overwrite`.
    pub const VM_READ_OVERWRITE: i32 = 3809;
    /// `vm_msync`.
    pub const VM_MSYNC: i32 = 3810;
    /// `vm_behavior_set`.
    pub const VM_BEHAVIOR_SET: i32 = 3811;
    /// `_kernelrpc_vm_map`.
    pub const KERNELRPC_VM_MAP: i32 = 3812;
    /// `vm_machine_attribute`.
    pub const VM_MACHINE_ATTRIBUTE: i32 = 3813;
    /// `_kernelrpc_vm_remap`.
    pub const KERNELRPC_VM_REMAP: i32 = 3814;
    /// `task_wire`.
    pub const TASK_WIRE: i32 = 3815;
    /// `mach_make_memory_entry`.
    pub const MACH_MAKE_MEMORY_ENTRY: i32 = 3816;
    /// `vm_map_page_query`.
    pub const VM_MAP_PAGE_QUERY: i32 = 3817;
    /// `mach_vm_region_info`.
    pub const MACH_VM_REGION_INFO: i32 = 3818;
    /// `vm_mapped_pages_info`.
    pub const VM_MAPPED_PAGES_INFO: i32 = 3819;
    /// `vm_region_recurse`.
    pub const VM_REGION_RECURSE: i32 = 3821;
    /// `vm_region_recurse_64`.
    pub const VM_REGION_RECURSE_64: i32 = 3822;
    /// `mach_vm_region_info_64`.
    pub const MACH_VM_REGION_INFO_64: i32 = 3823;
    /// `vm_region_64`.
    pub const VM_REGION_64: i32 = 3824;
    /// `mach_make_memory_entry_64`.
    pub const MACH_MAKE_MEMORY_ENTRY_64: i32 = 3825;
    /// `vm_map_64`.
    pub const VM_MAP_64: i32 = 3826;
    /// `_kernelrpc_vm_purgable_control`.
    pub const KERNELRPC_VM_PURGABLE_CONTROL: i32 = 3830;
    /// `vm_map_exec_lockdown`.
    pub const VM_MAP_EXEC_LOCKDOWN: i32 = 3831;
    /// `_kernelrpc_vm_remap_new`.
    pub const KERNELRPC_VM_REMAP_NEW: i32 = 3832;
    /// `_kernelrpc_vm_reallocate`.
    pub const KERNELRPC_VM_REALLOCATE: i32 = 3833;
}

/// Every routine by message ID, sorted (for tracing).
pub static NAMES: [(i32, &str); 277] = [
    (200, "host_info"),
    (201, "host_kernel_version"),
    (202, "_host_page_size"),
    (203, "mach_memory_object_memory_entry"),
    (204, "host_processor_info"),
    (205, "host_get_io_main"),
    (206, "host_get_clock_service"),
    (207, "kmod_get_info"),
    (209, "host_virtual_physical_table_info"),
    (213, "processor_set_default"),
    (214, "processor_set_create"),
    (215, "mach_memory_object_memory_entry_64"),
    (216, "host_statistics"),
    (217, "host_request_notification"),
    (218, "host_lockgroup_info"),
    (219, "host_statistics64"),
    (220, "mach_zone_info"),
    (222, "_kernelrpc_host_create_mach_voucher"),
    (223, "host_register_mach_voucher_attr_manager"),
    (224, "host_register_well_known_mach_voucher_attr_manager"),
    (225, "host_set_atm_diagnostic_flag"),
    (227, "mach_memory_info"),
    (228, "host_set_multiuser_config_flags"),
    (231, "mach_zone_info_for_zone"),
    (235, "mach_memory_info_redacted"),
    (400, "host_get_boot_info"),
    (401, "host_reboot"),
    (402, "host_priv_statistics"),
    (403, "host_default_memory_manager"),
    (404, "vm_wire"),
    (405, "thread_wire"),
    (406, "vm_allocate_cpm"),
    (407, "host_processors"),
    (408, "host_get_clock_control"),
    (409, "kmod_create"),
    (410, "kmod_destroy"),
    (411, "kmod_control"),
    (412, "host_get_special_port"),
    (413, "host_set_special_port"),
    (414, "host_set_exception_ports"),
    (415, "host_get_exception_ports"),
    (416, "host_swap_exception_ports"),
    (418, "mach_vm_wire"),
    (419, "host_processor_sets"),
    (420, "host_processor_set_priv"),
    (423, "host_set_UNDServer"),
    (424, "host_get_UNDServer"),
    (425, "kext_request"),
    (1000, "clock_get_time"),
    (1001, "clock_get_attributes"),
    (1002, "clock_alarm"),
    (3200, "mach_port_names"),
    (3201, "mach_port_type"),
    (3202, "mach_port_rename"),
    (3203, "mach_port_allocate_name"),
    (3204, "mach_port_allocate"),
    (3205, "mach_port_destroy"),
    (3206, "mach_port_deallocate"),
    (3207, "mach_port_get_refs"),
    (3208, "mach_port_mod_refs"),
    (3209, "mach_port_peek"),
    (3210, "mach_port_set_mscount"),
    (3211, "mach_port_get_set_status"),
    (3212, "mach_port_move_member"),
    (3213, "mach_port_request_notification"),
    (3214, "mach_port_insert_right"),
    (3215, "mach_port_extract_right"),
    (3216, "mach_port_set_seqno"),
    (3217, "mach_port_get_attributes"),
    (3218, "mach_port_set_attributes"),
    (3219, "mach_port_allocate_qos"),
    (3220, "mach_port_allocate_full"),
    (3221, "task_set_port_space"),
    (3222, "mach_port_get_srights"),
    (3223, "mach_port_space_info"),
    (3224, "mach_port_dnrequest_info"),
    (3225, "mach_port_kernel_object"),
    (3226, "mach_port_insert_member"),
    (3227, "mach_port_extract_member"),
    (3228, "mach_port_get_context"),
    (3229, "mach_port_set_context"),
    (3230, "mach_port_kobject"),
    (3231, "mach_port_construct"),
    (3232, "mach_port_destruct"),
    (3233, "mach_port_guard"),
    (3234, "mach_port_unguard"),
    (3235, "mach_port_space_basic_info"),
    (3236, "mach_port_special_reply_port_reset_link"),
    (3237, "mach_port_guard_with_flags"),
    (3238, "mach_port_swap_guard"),
    (3239, "mach_port_kobject_description"),
    (3240, "mach_port_is_connection_for_service"),
    (3241, "mach_port_get_service_port_info"),
    (3242, "mach_port_assert_attributes"),
    (3400, "task_create"),
    (3401, "task_terminate"),
    (3402, "task_threads"),
    (3403, "_kernelrpc_mach_ports_register3"),
    (3404, "_kernelrpc_mach_ports_lookup3"),
    (3405, "task_info"),
    (3406, "task_set_info"),
    (3407, "task_suspend"),
    (3408, "task_resume"),
    (3409, "task_get_special_port"),
    (3410, "task_set_special_port"),
    (3411, "thread_create"),
    (3412, "thread_create_running"),
    (3413, "task_set_exception_ports"),
    (3414, "task_get_exception_ports"),
    (3415, "task_swap_exception_ports"),
    (3416, "lock_set_create"),
    (3417, "lock_set_destroy"),
    (3418, "semaphore_create"),
    (3419, "semaphore_destroy"),
    (3420, "task_policy_set"),
    (3421, "task_policy_get"),
    (3422, "task_sample"),
    (3423, "task_policy"),
    (3424, "task_set_emulation"),
    (3425, "task_get_emulation_vector"),
    (3426, "task_set_emulation_vector"),
    (3427, "task_set_ras_pc"),
    (3428, "task_zone_info"),
    (3429, "task_assign"),
    (3430, "task_assign_default"),
    (3431, "task_get_assignment"),
    (3432, "task_set_policy"),
    (3433, "task_get_state"),
    (3434, "task_set_state"),
    (3435, "task_set_phys_footprint_limit"),
    (3436, "task_suspend2"),
    (3437, "task_resume2"),
    (3438, "task_purgable_info"),
    (3439, "task_get_mach_voucher"),
    (3440, "task_set_mach_voucher"),
    (3441, "task_swap_mach_voucher"),
    (3442, "task_generate_corpse"),
    (3443, "task_map_corpse_info"),
    (3444, "task_register_dyld_image_infos"),
    (3445, "task_unregister_dyld_image_infos"),
    (3446, "task_get_dyld_image_infos"),
    (3447, "task_register_dyld_shared_cache_image_info"),
    (3448, "task_register_dyld_set_dyld_state"),
    (3449, "task_register_dyld_get_process_state"),
    (3450, "task_map_corpse_info_64"),
    (3451, "task_inspect"),
    (3452, "task_get_exc_guard_behavior"),
    (3453, "task_set_exc_guard_behavior"),
    (3455, "_kernelrpc_mach_task_is_self"),
    (3456, "task_dyld_process_info_notify_register"),
    (3457, "task_create_identity_token"),
    (3458, "task_identity_token_get_task_port"),
    (3459, "task_dyld_process_info_notify_deregister"),
    (3460, "task_get_exception_ports_info"),
    (3461, "task_test_sync_upcall"),
    (3462, "task_set_corpse_forking_behavior"),
    (3463, "task_test_async_upcall_propagation"),
    (3464, "task_map_kcdata_object_64"),
    (3465, "task_register_hardened_exception_handler"),
    (3600, "thread_terminate"),
    (3601, "act_get_state"),
    (3602, "act_set_state"),
    (3603, "thread_get_state"),
    (3604, "thread_set_state"),
    (3605, "thread_suspend"),
    (3606, "thread_resume"),
    (3607, "thread_abort"),
    (3608, "thread_abort_safely"),
    (3609, "thread_depress_abort"),
    (3610, "thread_get_special_port"),
    (3611, "thread_set_special_port"),
    (3612, "thread_info"),
    (3613, "thread_set_exception_ports"),
    (3614, "thread_get_exception_ports"),
    (3615, "thread_swap_exception_ports"),
    (3616, "_kernelrpc_thread_policy"),
    (3617, "_kernelrpc_thread_policy_set"),
    (3618, "thread_policy_get"),
    (3619, "thread_sample"),
    (3620, "etap_trace_thread"),
    (3621, "thread_assign"),
    (3622, "thread_assign_default"),
    (3623, "thread_get_assignment"),
    (3624, "_kernelrpc_thread_set_policy"),
    (3625, "thread_get_mach_voucher"),
    (3626, "thread_set_mach_voucher"),
    (3627, "thread_swap_mach_voucher"),
    (3628, "thread_convert_thread_state"),
    (3630, "thread_get_exception_ports_info"),
    (3631, "thread_adopt_exception_handler"),
    (3632, "thread_suspend2"),
    (3633, "thread_resume2"),
    (3800, "vm_region"),
    (3804, "vm_inherit"),
    (3805, "_kernelrpc_vm_read"),
    (3806, "vm_read_list"),
    (3807, "vm_write"),
    (3808, "vm_copy"),
    (3809, "vm_read_overwrite"),
    (3810, "vm_msync"),
    (3811, "vm_behavior_set"),
    (3812, "_kernelrpc_vm_map"),
    (3813, "vm_machine_attribute"),
    (3814, "_kernelrpc_vm_remap"),
    (3815, "task_wire"),
    (3816, "mach_make_memory_entry"),
    (3817, "vm_map_page_query"),
    (3818, "mach_vm_region_info"),
    (3819, "vm_mapped_pages_info"),
    (3821, "vm_region_recurse"),
    (3822, "vm_region_recurse_64"),
    (3823, "mach_vm_region_info_64"),
    (3824, "vm_region_64"),
    (3825, "mach_make_memory_entry_64"),
    (3826, "vm_map_64"),
    (3830, "_kernelrpc_vm_purgable_control"),
    (3831, "vm_map_exec_lockdown"),
    (3832, "_kernelrpc_vm_remap_new"),
    (3833, "_kernelrpc_vm_reallocate"),
    (4000, "processor_set_statistics"),
    (4001, "processor_set_destroy"),
    (4002, "processor_set_max_priority"),
    (4003, "processor_set_policy_enable"),
    (4004, "processor_set_policy_disable"),
    (4005, "processor_set_tasks"),
    (4006, "processor_set_threads"),
    (4007, "processor_set_policy_control"),
    (4008, "processor_set_stack_usage"),
    (4009, "processor_set_info"),
    (4010, "processor_set_tasks_with_flavor"),
    (4800, "_kernelrpc_mach_vm_allocate"),
    (4801, "_kernelrpc_mach_vm_deallocate"),
    (4802, "_kernelrpc_mach_vm_protect"),
    (4803, "mach_vm_inherit"),
    (4804, "_kernelrpc_mach_vm_read"),
    (4805, "mach_vm_read_list"),
    (4806, "mach_vm_write"),
    (4807, "mach_vm_copy"),
    (4808, "mach_vm_read_overwrite"),
    (4809, "mach_vm_msync"),
    (4810, "mach_vm_behavior_set"),
    (4811, "_kernelrpc_mach_vm_map"),
    (4812, "mach_vm_machine_attribute"),
    (4813, "_kernelrpc_mach_vm_remap"),
    (4814, "mach_vm_page_query"),
    (4815, "mach_vm_region_recurse"),
    (4816, "mach_vm_region"),
    (4817, "mach_make_memory_entry"),
    (4818, "_kernelrpc_mach_vm_purgable_control"),
    (4819, "mach_vm_page_info"),
    (4820, "mach_vm_page_range_query"),
    (4821, "_kernelrpc_mach_vm_remap_new"),
    (4822, "mach_vm_deferred_reclamation_buffer_allocate"),
    (4823, "mach_vm_deferred_reclamation_buffer_flush"),
    (4825, "mach_vm_range_create"),
    (4826, "mach_vm_deferred_reclamation_buffer_resize"),
    (4827, "_kernelrpc_mach_vm_update_pointers_with_remote_tags"),
    (4828, "mach_vm_deferred_reclamation_buffer_query"),
    (4829, "_kernelrpc_mach_vm_reallocate"),
    (4900, "mach_memory_entry_purgable_control"),
    (4901, "mach_memory_entry_access_tracking"),
    (4902, "mach_memory_entry_ownership"),
    (4903, "mach_memory_entry_get_page_counts"),
    (5400, "mach_voucher_extract_attr_content"),
    (5401, "_kernelrpc_mach_voucher_extract_attr_recipe"),
    (5402, "mach_voucher_extract_all_attr_recipes"),
    (5403, "mach_voucher_attr_command"),
    (5404, "mach_voucher_debug_info"),
    (8000, "task_restartable_ranges_register"),
    (8001, "task_restartable_ranges_synchronize"),
    (617200, "semaphore_signal"),
    (617201, "semaphore_signal_all"),
    (617202, "semaphore_wait"),
    (617203, "semaphore_signal_thread"),
    (617204, "semaphore_timedwait"),
    (617205, "semaphore_wait_signal"),
    (617206, "semaphore_timedwait_signal"),
];

/// The routine name of request `id`.
pub fn name(id: i32) -> Option<&'static str> {
    NAMES
        .binary_search_by_key(&id, |e| e.0)
        .ok()
        .map(|i| NAMES[i].1)
}
